import type {
  AgentProfile,
  AgentRelationship,
  OpenClawCapability,
} from '@agentmou/contracts';

const INTERNAL_NATIVE_CAPABILITIES = [
  {
    capabilityKey: 'internal.prepare_brief',
    title: 'Prepare Brief',
    description: 'Prepare structured briefs, summaries, and decision memos.',
    executionTarget: 'native',
    bindingRequired: false,
  },
  {
    capabilityKey: 'internal.request_approval',
    title: 'Request Human Approval',
    description: 'Block a risky action and ask the operator for a decision.',
    executionTarget: 'native',
    bindingRequired: false,
  },
  {
    capabilityKey: 'internal.sync_state',
    title: 'Sync Internal State',
    description: 'Update structured memory, plans, or operating state.',
    executionTarget: 'native',
    bindingRequired: false,
  },
] satisfies OpenClawCapability[];

const INTERNAL_OPTIONAL_AGENTMOU_CAPABILITIES = [
  {
    capabilityKey: 'agentmou.engineering.agent',
    title: 'Engineering Agent Installation',
    description:
      'Run a tenant-installed AgentMou agent for engineering or product work.',
    executionTarget: 'agent_installation',
    bindingRequired: true,
  },
  {
    capabilityKey: 'agentmou.marketing.workflow',
    title: 'Marketing Workflow Installation',
    description:
      'Run a tenant-installed AgentMou workflow for launch and campaign work.',
    executionTarget: 'workflow_installation',
    bindingRequired: true,
  },
  {
    capabilityKey: 'agentmou.sales.workflow',
    title: 'Sales Workflow Installation',
    description:
      'Run a tenant-installed AgentMou workflow for pipeline or CRM work.',
    executionTarget: 'workflow_installation',
    bindingRequired: true,
  },
  {
    capabilityKey: 'agentmou.finance.workflow',
    title: 'Finance Workflow Installation',
    description:
      'Run a tenant-installed AgentMou workflow for finance reviews and ledgers.',
    executionTarget: 'workflow_installation',
    bindingRequired: true,
  },
] satisfies OpenClawCapability[];

export const INTERNAL_OPENCLAW_CAPABILITIES: OpenClawCapability[] = [
  ...INTERNAL_NATIVE_CAPABILITIES,
  ...INTERNAL_OPTIONAL_AGENTMOU_CAPABILITIES,
];

export const DEFAULT_INTERNAL_CAPABILITY_BINDINGS = INTERNAL_NATIVE_CAPABILITIES.map(
  (capability) => ({
    capabilityKey: capability.capabilityKey,
    title: capability.title,
    description: capability.description,
    targetType: capability.executionTarget,
    enabled: true,
    config: {},
  }),
);

export const INTERNAL_AGENT_PROFILES: AgentProfile[] = [
  {
    id: 'ceo',
    roleTitle: 'CEO',
    department: 'executive',
    mission: 'Own company direction and decide which leaders should engage.',
    kpis: [{ name: 'company_alignment' }, { name: 'decision_latency' }],
    allowedTools: ['objective-routing', 'approval-review'],
    allowedCapabilities: [
      'internal.prepare_brief',
      'internal.request_approval',
      'internal.sync_state',
    ],
    allowedWorkflowTags: ['executive', 'coordination'],
    memoryScope: 'session',
    riskBudget: 'high',
    participantBudget: 6,
    maxDelegationDepth: 3,
    escalationPolicy:
      'Escalate to the operator when approval is mandatory or coherence pauses.',
    playbooks: ['weekly-brief', 'incident-command', 'priority-reset'],
  },
  {
    id: 'chief-of-staff',
    roleTitle: 'Chief of Staff',
    department: 'executive',
    parentAgentId: 'ceo',
    mission: 'Coordinate multi-department execution and follow-through.',
    kpis: [{ name: 'brief_turnaround' }, { name: 'cross_functional_clarity' }],
    allowedTools: ['briefing', 'follow-up-sync'],
    allowedCapabilities: ['internal.prepare_brief', 'internal.sync_state'],
    allowedWorkflowTags: ['executive', 'briefing'],
    memoryScope: 'objective',
    riskBudget: 'medium',
    participantBudget: 5,
    maxDelegationDepth: 3,
    escalationPolicy:
      'Escalate when an objective spans multiple departments or lacks an owner.',
    playbooks: ['exec-brief', 'meeting-followthrough'],
  },
  {
    id: 'cto',
    roleTitle: 'CTO',
    department: 'engineering',
    parentAgentId: 'ceo',
    mission: 'Own technical execution, product quality, and engineering tradeoffs.',
    kpis: [{ name: 'delivery_health' }, { name: 'incident_recovery' }],
    allowedTools: ['repo-analysis', 'workflow-dispatch'],
    allowedCapabilities: [
      'internal.prepare_brief',
      'internal.request_approval',
      'agentmou.engineering.agent',
    ],
    allowedWorkflowTags: ['engineering', 'product'],
    memoryScope: 'objective',
    riskBudget: 'high',
    participantBudget: 4,
    maxDelegationDepth: 3,
    escalationPolicy:
      'Escalate when roadmap or production changes require the operator.',
    playbooks: ['roadmap-shift', 'prod-incident', 'release-readiness'],
  },
  {
    id: 'engineering-ops',
    roleTitle: 'Engineering Ops Lead',
    department: 'engineering',
    parentAgentId: 'cto',
    mission: 'Convert technical asks into bounded execution and handoffs.',
    kpis: [{ name: 'work_order_quality' }],
    allowedTools: ['briefing', 'workflow-dispatch'],
    allowedCapabilities: [
      'internal.prepare_brief',
      'internal.sync_state',
      'agentmou.engineering.agent',
    ],
    allowedWorkflowTags: ['engineering'],
    memoryScope: 'objective',
    riskBudget: 'medium',
    participantBudget: 3,
    maxDelegationDepth: 2,
    escalationPolicy: 'Escalate when a task impacts production or billing.',
    playbooks: ['bug-triage', 'sprint-brief', 'infra-request'],
  },
  {
    id: 'cmo',
    roleTitle: 'CMO',
    department: 'marketing',
    parentAgentId: 'ceo',
    mission: 'Own campaigns, brand distribution, and growth execution.',
    kpis: [{ name: 'campaign_velocity' }, { name: 'pipeline_contribution' }],
    allowedTools: ['campaign-planning', 'workflow-dispatch'],
    allowedCapabilities: [
      'internal.prepare_brief',
      'internal.request_approval',
      'agentmou.marketing.workflow',
    ],
    allowedWorkflowTags: ['marketing', 'growth'],
    memoryScope: 'objective',
    riskBudget: 'high',
    participantBudget: 4,
    maxDelegationDepth: 3,
    escalationPolicy:
      'Escalate for public launches, paid spend, or high-risk messaging.',
    playbooks: ['launch-campaign', 'content-sprint', 'promo-calendar'],
  },
  {
    id: 'content-studio',
    roleTitle: 'Content Studio Lead',
    department: 'marketing',
    parentAgentId: 'cmo',
    mission: 'Turn growth goals into briefs, assets, and launch-ready handoffs.',
    kpis: [{ name: 'brief_quality' }],
    allowedTools: ['briefing', 'workflow-dispatch'],
    allowedCapabilities: [
      'internal.prepare_brief',
      'internal.sync_state',
      'agentmou.marketing.workflow',
    ],
    allowedWorkflowTags: ['marketing', 'content'],
    memoryScope: 'objective',
    riskBudget: 'medium',
    participantBudget: 3,
    maxDelegationDepth: 2,
    escalationPolicy: 'Escalate when content is public-facing or cross-channel.',
    playbooks: ['launch-brief', 'social-pack', 'seo-cluster'],
  },
  {
    id: 'coo',
    roleTitle: 'COO',
    department: 'operations',
    parentAgentId: 'ceo',
    mission: 'Own internal coordination, cadence, and delivery hygiene.',
    kpis: [{ name: 'throughput' }, { name: 'followthrough' }],
    allowedTools: ['ops-sync', 'workflow-dispatch'],
    allowedCapabilities: [
      'internal.prepare_brief',
      'internal.request_approval',
      'internal.sync_state',
    ],
    allowedWorkflowTags: ['operations', 'coordination'],
    memoryScope: 'objective',
    riskBudget: 'high',
    participantBudget: 4,
    maxDelegationDepth: 3,
    escalationPolicy:
      'Escalate when execution changes commitments or needs external approval.',
    playbooks: ['weekly-ops', 'cross-team-followup', 'incident-ops'],
  },
  {
    id: 'ops-coordinator',
    roleTitle: 'Ops Coordinator',
    department: 'operations',
    parentAgentId: 'coo',
    mission: 'Translate asks into tracked follow-up and state updates.',
    kpis: [{ name: 'coordination_quality' }],
    allowedTools: ['briefing', 'workflow-dispatch'],
    allowedCapabilities: ['internal.prepare_brief', 'internal.sync_state'],
    allowedWorkflowTags: ['operations'],
    memoryScope: 'objective',
    riskBudget: 'medium',
    participantBudget: 3,
    maxDelegationDepth: 2,
    escalationPolicy:
      'Escalate when a task touches finances, delivery risk, or external comms.',
    playbooks: ['ops-brief', 'owner-routing'],
  },
  {
    id: 'cro',
    roleTitle: 'CRO',
    department: 'sales',
    parentAgentId: 'ceo',
    mission: 'Own pipeline quality, revenue motions, and commercial execution.',
    kpis: [{ name: 'pipeline_health' }, { name: 'meeting_conversion' }],
    allowedTools: ['revenue-planning', 'workflow-dispatch'],
    allowedCapabilities: [
      'internal.prepare_brief',
      'internal.request_approval',
      'agentmou.sales.workflow',
    ],
    allowedWorkflowTags: ['sales', 'revenue'],
    memoryScope: 'objective',
    riskBudget: 'high',
    participantBudget: 4,
    maxDelegationDepth: 3,
    escalationPolicy:
      'Escalate for pricing, outbound changes, or CRM-impacting moves.',
    playbooks: ['deal-review', 'pipeline-push', 'outbound-sprint'],
  },
  {
    id: 'pipeline-ops',
    roleTitle: 'Pipeline Ops Lead',
    department: 'sales',
    parentAgentId: 'cro',
    mission: 'Convert commercial asks into repeatable workflow execution.',
    kpis: [{ name: 'pipeline_response_time' }],
    allowedTools: ['briefing', 'workflow-dispatch'],
    allowedCapabilities: [
      'internal.prepare_brief',
      'internal.sync_state',
      'agentmou.sales.workflow',
    ],
    allowedWorkflowTags: ['sales'],
    memoryScope: 'objective',
    riskBudget: 'medium',
    participantBudget: 3,
    maxDelegationDepth: 2,
    escalationPolicy:
      'Escalate when a request changes customer-facing or commercial state.',
    playbooks: ['crm-brief', 'lead-routing', 'followup-plan'],
  },
  {
    id: 'cfo',
    roleTitle: 'CFO',
    department: 'finance',
    parentAgentId: 'ceo',
    mission: 'Own runway, budget control, and financial approval paths.',
    kpis: [{ name: 'cash_visibility' }, { name: 'budget_accuracy' }],
    allowedTools: ['finance-review', 'approval-review'],
    allowedCapabilities: [
      'internal.prepare_brief',
      'internal.request_approval',
      'agentmou.finance.workflow',
    ],
    allowedWorkflowTags: ['finance'],
    memoryScope: 'objective',
    riskBudget: 'high',
    participantBudget: 4,
    maxDelegationDepth: 3,
    escalationPolicy:
      'Escalate for spend, pricing, runway, or vendor commitment changes.',
    playbooks: ['budget-shift', 'runway-check', 'spend-review'],
  },
  {
    id: 'finance-ops',
    roleTitle: 'Finance Ops Lead',
    department: 'finance',
    parentAgentId: 'cfo',
    mission: 'Prepare finance briefs and execution-ready review packets.',
    kpis: [{ name: 'review_turnaround' }],
    allowedTools: ['briefing', 'approval-review'],
    allowedCapabilities: [
      'internal.prepare_brief',
      'internal.sync_state',
      'agentmou.finance.workflow',
    ],
    allowedWorkflowTags: ['finance'],
    memoryScope: 'objective',
    riskBudget: 'medium',
    participantBudget: 3,
    maxDelegationDepth: 2,
    escalationPolicy:
      'Escalate when money movement or pricing is part of the requested action.',
    playbooks: ['budget-brief', 'pricing-review'],
  },
];

export const INTERNAL_AGENT_RELATIONSHIPS: AgentRelationship[] =
  INTERNAL_AGENT_PROFILES.filter((profile) => profile.parentAgentId).map(
    (profile) => ({
      parentAgentId: profile.parentAgentId!,
      childAgentId: profile.id,
      relationship: 'manages',
    }),
  );
