export const INTEGRATION_LOGO_LOOP = [
  { id: 'n8n', src: '/integrations/n8n.svg', name: 'n8n', href: 'https://n8n.io' },
  { id: 'openai', src: '/integrations/openai.svg', name: 'OpenAI', href: 'https://openai.com' },
  { id: 'gmail', src: '/integrations/gmail.svg', name: 'Gmail', href: 'https://gmail.com' },
  { id: 'notion', src: '/integrations/notion.svg', name: 'Notion', href: 'https://notion.so' },
  { id: 'tiktok', src: '/integrations/tiktok.svg', name: 'TikTok', href: 'https://tiktok.com' },
  { id: 'anthropic', src: '/integrations/anthropic.svg', name: 'Anthropic', href: 'https://anthropic.com' },
  { id: 'google-drive', src: '/integrations/google-drive.svg', name: 'Google Drive', href: 'https://drive.google.com' },
  { id: 'linkedin', src: '/integrations/linkedin.svg', name: 'LinkedIn', href: 'https://linkedin.com' },
  { id: 'slack', src: '/integrations/slack.svg', name: 'Slack', href: 'https://slack.com' },
  { id: 'shopify', src: '/integrations/shopify.svg', name: 'Shopify', href: 'https://shopify.com' },
  { id: 'google-gemini', src: '/integrations/google-gemini.svg', name: 'Google Gemini', href: 'https://gemini.google.com' },
  { id: 'whatsapp-business', src: '/integrations/whatsapp-business.svg', name: 'WhatsApp Business', href: 'https://business.whatsapp.com' },
  { id: 'google-sheets', src: '/integrations/google-sheets.svg', name: 'Google Sheets', href: 'https://sheets.google.com' },
  { id: 'x', src: '/integrations/x.svg', name: 'X', href: 'https://x.com' },
  { id: 'hubspot', src: '/integrations/hubspot.svg', name: 'HubSpot', href: 'https://hubspot.com' },
] as const
