import type {
  Tenant,
  AgentTemplate,
  WorkflowTemplate,
  PackTemplate,
  Integration,
  InstalledAgent,
  InstalledWorkflow,
  ApprovalRequest,
  ExecutionRun,
  SecurityFinding,
  SecurityPolicy,
  TenantMember,
  Invoice,
  DashboardMetrics,
  N8nConnection,
} from '../control-plane/types';

// Import catalog modules
import { newWorkflowTemplates } from './catalog/workflows-public';
import { plannedWorkflowTemplates } from './catalog/workflows-planned';
import { coreAgentTemplates } from './catalog/agents-core';
import { supportAgentTemplates } from './catalog/agents-support';
import { salesAgentTemplates } from './catalog/agents-sales';
import { researchAgentTemplates } from './catalog/agents-research';
import { personalAgentTemplates } from './catalog/agents-personal';
import { opsFinanceAgentTemplates } from './catalog/agents-ops-finance';
import { newIntegrations } from './catalog/integrations';

// Tenants
export const tenants: Tenant[] = [
  {
    id: 'demo-workspace',
    name: 'Demo Workspace',
    type: 'business',
    plan: 'pro',
    createdAt: '2024-01-01T00:00:00Z',
    ownerId: 'demo-user',
    settings: {
      timezone: 'America/New_York',
      defaultHITL: true,
      logRetentionDays: 30,
      memoryRetentionDays: 7,
      activeVertical: 'clinic',
      isPlatformAdminTenant: false,
      settingsVersion: 2,
      verticalClinicUi: true,
      clinicDentalMode: true,
      internalPlatformVisible: false,
    },
  },
  {
    id: 'tenant-acme',
    name: 'Acme Corp',
    type: 'business',
    plan: 'pro',
    createdAt: '2024-01-15T10:00:00Z',
    ownerId: 'user-1',
    settings: {
      timezone: 'Europe/Madrid',
      defaultHITL: true,
      logRetentionDays: 30,
      memoryRetentionDays: 7,
      activeVertical: 'internal',
      isPlatformAdminTenant: false,
      settingsVersion: 2,
      verticalClinicUi: false,
      clinicDentalMode: false,
      internalPlatformVisible: false,
    },
  },
  {
    id: 'tenant-personal',
    name: 'My Workspace',
    type: 'personal',
    plan: 'starter',
    createdAt: '2024-02-20T14:30:00Z',
    ownerId: 'user-1',
    settings: {
      timezone: 'America/New_York',
      defaultHITL: false,
      logRetentionDays: 7,
      memoryRetentionDays: 0,
      activeVertical: 'internal',
      isPlatformAdminTenant: false,
      settingsVersion: 2,
      verticalClinicUi: false,
      clinicDentalMode: false,
      internalPlatformVisible: false,
    },
  },
  {
    id: 'tenant-fisio',
    name: 'Fisio Pilot Workspace',
    type: 'business',
    plan: 'starter',
    createdAt: '2024-03-01T09:00:00Z',
    ownerId: 'user-2',
    settings: {
      timezone: 'Europe/Madrid',
      defaultHITL: false,
      logRetentionDays: 30,
      memoryRetentionDays: 7,
      activeVertical: 'fisio',
      isPlatformAdminTenant: false,
      settingsVersion: 2,
      verticalClinicUi: false,
      clinicDentalMode: false,
      internalPlatformVisible: false,
    },
  },
];

// Workflow Templates (n8n assets) - MVP list from prompt
export const workflowTemplates: WorkflowTemplate[] = [
  {
    id: 'wf-01',
    name: 'Auto-label Gmail with AI',
    summary: 'Automatically categorize and label incoming emails using AI classification',
    trigger: 'email',
    integrations: ['gmail', 'openai'],
    output: 'Labeled emails in Gmail with AI-determined categories',
    useCase: 'Reduce inbox clutter and enable smart filtering for high-priority emails',
    riskLevel: 'low',
    version: '1.2.0',
    changelog: [
      '1.2.0: Added multi-label support',
      '1.1.0: Improved accuracy',
      '1.0.0: Initial release',
    ],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Gmail Trigger', description: 'New email received' },
      { id: 'n2', type: 'ai', name: 'OpenAI Classifier', description: 'Classify email content' },
      { id: 'n3', type: 'action', name: 'Gmail Labels', description: 'Apply labels' },
    ],
    availability: 'available',
  },
  {
    id: 'wf-02',
    name: 'Slack to Linear Ticketing with Dedupe',
    summary: 'Convert Slack messages to Linear tickets with intelligent deduplication',
    trigger: 'event',
    integrations: ['slack', 'linear'],
    output: 'Linear tickets created from Slack with dedupe checks',
    useCase: 'Streamline support requests from Slack without duplicate tickets',
    riskLevel: 'low',
    version: '2.0.0',
    changelog: ['2.0.0: Added dedupe ledger', '1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Slack Event', description: 'Message with reaction' },
      { id: 'n2', type: 'logic', name: 'Dedupe Check', description: 'Check existing tickets' },
      { id: 'n3', type: 'action', name: 'Linear Create', description: 'Create ticket' },
    ],
    availability: 'available',
  },
  {
    id: 'wf-03',
    name: 'RSS to Sheets Summarize to Slack',
    summary: 'Monitor RSS feeds, dedupe entries, summarize with AI, post to Slack',
    trigger: 'cron',
    integrations: ['rss', 'google-sheets', 'openai', 'slack'],
    output: 'Daily digest of new RSS items summarized and posted to Slack',
    useCase: 'Stay informed on industry news without manual reading',
    riskLevel: 'low',
    version: '1.5.0',
    changelog: ['1.5.0: Added Sheets dedup ledger', '1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Schedule', description: 'Daily at 9am' },
      { id: 'n2', type: 'fetch', name: 'RSS Fetch', description: 'Get feed items' },
      { id: 'n3', type: 'logic', name: 'Dedupe', description: 'Check Sheets ledger' },
      { id: 'n4', type: 'ai', name: 'Summarize', description: 'AI summary' },
      { id: 'n5', type: 'action', name: 'Slack Post', description: 'Send digest' },
    ],
    availability: 'available',
  },
  {
    id: 'wf-04',
    name: 'Meeting Prep (Apify + AI) to WhatsApp',
    summary: 'Research meeting attendees and send briefing via WhatsApp',
    trigger: 'cron',
    integrations: ['google-calendar', 'apify', 'openai', 'whatsapp'],
    output: 'Pre-meeting briefing delivered to WhatsApp',
    useCase: 'Never go into a meeting unprepared',
    riskLevel: 'medium',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Calendar Check', description: 'Upcoming meetings' },
      { id: 'n2', type: 'fetch', name: 'Apify Scrape', description: 'Research attendees' },
      { id: 'n3', type: 'ai', name: 'Generate Brief', description: 'Create briefing' },
      { id: 'n4', type: 'action', name: 'WhatsApp Send', description: 'Deliver brief' },
    ],
    availability: 'available',
  },
  {
    id: 'wf-05',
    name: 'Competitor Research to Notion',
    summary: 'Use Exa + SerpAPI + AI to research competitors and update Notion',
    trigger: 'cron',
    integrations: ['exa', 'serpapi', 'openai', 'notion'],
    output: 'Structured competitor intel in Notion database',
    useCase: 'Automated competitive intelligence gathering',
    riskLevel: 'low',
    version: '1.3.0',
    changelog: ['1.3.0: Added sentiment analysis', '1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Weekly Schedule', description: 'Every Monday' },
      { id: 'n2', type: 'fetch', name: 'Exa Search', description: 'Find mentions' },
      { id: 'n3', type: 'fetch', name: 'SerpAPI', description: 'SERP data' },
      { id: 'n4', type: 'ai', name: 'Analyze', description: 'Extract insights' },
      { id: 'n5', type: 'action', name: 'Notion Update', description: 'Update database' },
    ],
    availability: 'available',
  },
  {
    id: 'wf-09',
    name: 'Scrape & Summarize Webpages',
    summary: 'Scrape any webpage and generate a structured summary',
    trigger: 'webhook',
    integrations: ['apify', 'openai'],
    output: 'Structured summary of webpage content',
    useCase: 'Quick research on any webpage via API call',
    riskLevel: 'low',
    version: '1.1.0',
    changelog: ['1.1.0: Added structured output', '1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Webhook', description: 'Receive URL' },
      { id: 'n2', type: 'fetch', name: 'Apify Scrape', description: 'Extract content' },
      { id: 'n3', type: 'ai', name: 'Summarize', description: 'Generate summary' },
    ],
    availability: 'available',
  },
  {
    id: 'wf-10',
    name: 'Trustpilot Reviews Sentiment',
    summary: 'Monitor Trustpilot reviews and analyze sentiment trends',
    trigger: 'cron',
    integrations: ['trustpilot', 'openai', 'google-sheets'],
    output: 'Sentiment scores and trends in Sheets',
    useCase: 'Track customer sentiment over time',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Daily Schedule', description: 'Every day 8am' },
      { id: 'n2', type: 'fetch', name: 'Trustpilot API', description: 'Get reviews' },
      { id: 'n3', type: 'ai', name: 'Sentiment', description: 'Analyze sentiment' },
      { id: 'n4', type: 'action', name: 'Sheets Update', description: 'Log results' },
    ],
    availability: 'available',
  },
  {
    id: 'wf-24',
    name: 'Gmail + Calendar Coordinator',
    summary: 'Process email requests and coordinate with Google Calendar',
    trigger: 'email',
    integrations: ['gmail', 'google-calendar', 'openai'],
    output: 'Automatic meeting scheduling from email requests',
    useCase: 'Let AI handle meeting scheduling requests',
    riskLevel: 'medium',
    version: '1.2.0',
    changelog: ['1.2.0: Added conflict detection', '1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Gmail Trigger', description: 'Meeting request emails' },
      { id: 'n2', type: 'ai', name: 'Parse Request', description: 'Extract details' },
      { id: 'n3', type: 'logic', name: 'Check Calendar', description: 'Find slots' },
      { id: 'n4', type: 'action', name: 'Create Event', description: 'Book meeting' },
    ],
    availability: 'available',
  },
  {
    id: 'wf-25',
    name: 'Gmail Attachments Evaluator',
    summary: 'Evaluate email attachments and log results to Sheets',
    trigger: 'email',
    integrations: ['gmail', 'openai', 'google-sheets'],
    output: 'Evaluation scores in Google Sheets',
    useCase: 'Automated document/resume screening',
    riskLevel: 'medium',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Gmail Trigger', description: 'Emails with attachments' },
      { id: 'n2', type: 'extract', name: 'Parse Attachment', description: 'Extract text' },
      { id: 'n3', type: 'ai', name: 'Evaluate', description: 'Score document' },
      { id: 'n4', type: 'action', name: 'Log to Sheets', description: 'Record results' },
    ],
    availability: 'available',
  },
  {
    id: 'wf-26',
    name: 'Gmail Attachments to Drive',
    summary: 'Automatically archive email attachments to Google Drive',
    trigger: 'email',
    integrations: ['gmail', 'google-drive'],
    output: 'Organized attachments in Drive folders',
    useCase: 'Never lose an important attachment',
    riskLevel: 'low',
    version: '1.1.0',
    changelog: ['1.1.0: Added folder organization', '1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Gmail Trigger', description: 'Emails with attachments' },
      { id: 'n2', type: 'logic', name: 'Filter', description: 'Check file types' },
      { id: 'n3', type: 'action', name: 'Upload to Drive', description: 'Save files' },
    ],
    availability: 'available',
  },
  // Merge in new workflows from catalog
  ...newWorkflowTemplates,
  // Merge in planned workflow placeholders
  ...plannedWorkflowTemplates,
];

// Agent Templates - MVP list from prompt
export const agentTemplates: AgentTemplate[] = [
  {
    id: 'agent-inbox-triage',
    name: 'Inbox Triage & Draft Reply',
    outcome: 'Reduce email response time by 70%',
    domain: 'support',
    description:
      'Automatically categorizes incoming emails, drafts appropriate responses, and flags urgent items for human review.',
    inputs: ['email_content', 'sender_info', 'thread_history'],
    outputs: ['category', 'priority', 'draft_reply', 'suggested_action'],
    requiredIntegrations: ['gmail', 'openai'],
    workflows: ['wf-01'],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Response Time', description: 'Average time to first response' },
      { name: 'Deflection Rate', description: 'Emails handled without human intervention' },
    ],
    complexity: 'M',
    version: '2.1.0',
    channel: 'stable',
    setupTimeMinutes: 15,
    monthlyPrice: null,
    availability: 'available',
    audience: 'both',
    // Catalog organization
    catalogGroup: 'support',
    family: 'inbox-intake',
    tags: ['email', 'triage', 'draft-reply'],
    featured: true,
    visibility: 'public',
  },
  {
    id: 'agent-ticket-router',
    name: 'Support Ticket Router',
    outcome: 'Route 95% of tickets to the right team instantly',
    domain: 'support',
    description:
      'Analyzes incoming support tickets, categorizes by topic and urgency, and routes to the appropriate team with full context.',
    inputs: ['ticket_subject', 'ticket_body', 'customer_context'],
    outputs: ['category', 'priority', 'assigned_team', 'suggested_response'],
    requiredIntegrations: ['slack', 'linear'],
    workflows: ['wf-02'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Routing Accuracy', description: 'Correct team assignment rate' },
      { name: 'Time to Assignment', description: 'Seconds from ticket to assignment' },
    ],
    complexity: 'S',
    version: '2.0.0',
    channel: 'stable',
    setupTimeMinutes: 10,
    monthlyPrice: null,
    availability: 'available',
    audience: 'business',
    // Catalog organization
    catalogGroup: 'support',
    family: 'ticketing',
    tags: ['ticketing', 'routing', 'slack', 'linear'],
    featured: true,
    visibility: 'public',
  },
  {
    id: 'agent-market-monitor',
    name: 'Market Monitor Digest',
    outcome: 'Never miss industry news that matters',
    domain: 'research',
    description:
      'Monitors RSS feeds and news sources, filters for relevance, and delivers a daily digest with AI-generated summaries.',
    inputs: ['rss_feeds', 'keywords', 'competitors'],
    outputs: ['digest', 'highlights', 'action_items'],
    requiredIntegrations: ['rss', 'google-sheets', 'slack'],
    workflows: ['wf-03'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Relevance Score', description: 'User-rated relevance of digest items' },
      { name: 'Time Saved', description: 'Hours saved on manual research' },
    ],
    complexity: 'M',
    version: '1.5.0',
    channel: 'stable',
    setupTimeMinutes: 20,
    monthlyPrice: null,
    availability: 'available',
    audience: 'both',
    // Catalog organization
    catalogGroup: 'research',
    family: 'research-intel',
    tags: ['research', 'news', 'rss', 'digest'],
    featured: true,
    visibility: 'public',
  },
  {
    id: 'agent-meeting-prep',
    name: 'Meeting Prep Briefing',
    outcome: 'Walk into every meeting fully prepared',
    domain: 'sales',
    description:
      'Researches upcoming meeting attendees, compiles relevant information, and delivers a briefing before your meeting.',
    inputs: ['calendar_event', 'attendee_emails'],
    outputs: ['briefing_doc', 'talking_points', 'potential_questions'],
    requiredIntegrations: ['google-calendar', 'apify', 'whatsapp'],
    workflows: ['wf-04'],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Prep Coverage', description: 'Meetings with briefings delivered' },
      { name: 'Meeting Success', description: 'Positive meeting outcomes' },
    ],
    complexity: 'L',
    version: '1.0.0',
    channel: 'beta',
    setupTimeMinutes: 30,
    monthlyPrice: 29,
    availability: 'available',
    audience: 'business',
    // Catalog organization
    catalogGroup: 'sales',
    family: 'meeting-scheduling',
    tags: ['meeting', 'prep', 'calendar', 'research'],
    featured: true,
    visibility: 'public',
  },
  {
    id: 'agent-competitor-intel',
    name: 'Competitor Intel to Notion',
    outcome: 'Automated competitive intelligence on autopilot',
    domain: 'research',
    description:
      'Continuously monitors competitors using search APIs and AI, updating a structured Notion database with insights.',
    inputs: ['competitor_list', 'tracking_keywords'],
    outputs: ['intel_report', 'trend_analysis', 'alerts'],
    requiredIntegrations: ['exa', 'serpapi', 'notion'],
    workflows: ['wf-05'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Intel Freshness', description: 'Average age of competitive data' },
      { name: 'Actionable Insights', description: 'Insights leading to decisions' },
    ],
    complexity: 'M',
    version: '1.3.0',
    channel: 'stable',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'available',
    audience: 'business',
    // Catalog organization
    catalogGroup: 'research',
    family: 'research-intel',
    tags: ['competitive-intel', 'research', 'monitoring'],
    featured: true,
    visibility: 'public',
  },
  {
    id: 'agent-webpage-summarizer',
    name: 'Web Page Summarizer',
    outcome: 'Get the gist of any webpage in seconds',
    domain: 'research',
    description: 'On-demand webpage scraping and summarization via API or Slack command.',
    inputs: ['url'],
    outputs: ['summary', 'key_points', 'entities'],
    requiredIntegrations: ['apify'],
    workflows: ['wf-09'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Summary Quality', description: 'User satisfaction rating' },
      { name: 'Processing Time', description: 'Seconds to deliver summary' },
    ],
    complexity: 'S',
    version: '1.1.0',
    channel: 'stable',
    setupTimeMinutes: 5,
    monthlyPrice: null,
    availability: 'available',
    audience: 'both',
    // Catalog organization
    catalogGroup: 'research',
    family: 'research-intel',
    tags: ['scraping', 'summarization', 'research'],
    visibility: 'public',
  },
  {
    id: 'agent-sentiment-tracker',
    name: 'Trustpilot Sentiment Tracker',
    outcome: 'Track customer sentiment trends automatically',
    domain: 'support',
    description:
      'Monitors Trustpilot reviews, analyzes sentiment, and tracks trends over time with alerts for negative spikes.',
    inputs: ['trustpilot_url'],
    outputs: ['sentiment_score', 'trend', 'alerts', 'summary'],
    requiredIntegrations: ['trustpilot', 'google-sheets'],
    workflows: ['wf-10'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Sentiment Accuracy', description: 'Correlation with manual analysis' },
      { name: 'Alert Speed', description: 'Time to alert on negative trends' },
    ],
    complexity: 'S',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 10,
    monthlyPrice: null,
    availability: 'available',
    audience: 'business',
    // Catalog organization
    catalogGroup: 'support',
    family: 'reviews-sentiment',
    tags: ['reviews', 'sentiment', 'analytics', 'trustpilot'],
    featured: true,
    visibility: 'public',
  },
  {
    id: 'agent-calendar-resolver',
    name: 'Calendar Conflict Resolver',
    outcome: 'Never double-book again',
    domain: 'sales',
    description:
      'Monitors calendar for conflicts, suggests resolutions, and can automatically reschedule with approval.',
    inputs: ['calendar_events'],
    outputs: ['conflicts', 'suggestions', 'auto_resolved'],
    requiredIntegrations: ['gmail', 'google-calendar'],
    workflows: ['wf-24'],
    riskLevel: 'medium',
    hitl: 'required',
    kpis: [
      { name: 'Conflicts Resolved', description: 'Auto-resolved scheduling conflicts' },
      { name: 'Time Saved', description: 'Hours saved on manual coordination' },
    ],
    complexity: 'M',
    version: '1.2.0',
    channel: 'stable',
    setupTimeMinutes: 15,
    monthlyPrice: null,
    availability: 'available',
    audience: 'both',
    // Catalog organization
    catalogGroup: 'sales',
    family: 'meeting-scheduling',
    tags: ['calendar', 'scheduling', 'conflicts'],
    visibility: 'public',
  },
  {
    id: 'agent-resume-evaluator',
    name: 'Resume/Attachment Evaluator',
    outcome: 'Screen documents 10x faster',
    domain: 'support',
    description:
      'Evaluates email attachments (resumes, applications, documents) against criteria and logs results.',
    inputs: ['attachment', 'evaluation_criteria'],
    outputs: ['score', 'highlights', 'concerns', 'recommendation'],
    requiredIntegrations: ['gmail', 'google-sheets'],
    workflows: ['wf-25'],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Screening Time', description: 'Time per document screened' },
      { name: 'Accuracy', description: 'Agreement with human reviewers' },
    ],
    complexity: 'M',
    version: '1.0.0',
    channel: 'beta',
    setupTimeMinutes: 20,
    monthlyPrice: 19,
    availability: 'available',
    audience: 'business',
    // Catalog organization
    catalogGroup: 'ops',
    family: 'documents-attachments',
    tags: ['documents', 'evaluation', 'hr', 'hiring'],
    visibility: 'public',
  },
  {
    id: 'agent-attachment-archiver',
    name: 'Attachment Archiver',
    outcome: 'Never lose an important attachment',
    domain: 'support',
    description:
      'Automatically archives email attachments to organized Google Drive folders based on sender and content.',
    inputs: ['email_attachments'],
    outputs: ['archived_files', 'folder_path'],
    requiredIntegrations: ['gmail', 'google-drive'],
    workflows: ['wf-26'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Files Archived', description: 'Total attachments saved' },
      { name: 'Organization', description: 'Files findable within 30s' },
    ],
    complexity: 'S',
    version: '1.1.0',
    channel: 'stable',
    setupTimeMinutes: 10,
    monthlyPrice: null,
    availability: 'available',
    audience: 'both',
    // Catalog organization
    catalogGroup: 'support',
    family: 'documents-attachments',
    tags: ['attachments', 'archiving', 'drive', 'email'],
    visibility: 'public',
  },
  // Merge in new agents from catalog
  ...coreAgentTemplates,
  ...supportAgentTemplates,
  ...salesAgentTemplates,
  ...researchAgentTemplates,
  ...personalAgentTemplates,
  ...opsFinanceAgentTemplates,
];

// Packs - 6 outcome-based packs covering key use cases
export const packTemplates: PackTemplate[] = [
  {
    id: 'pack-support-starter',
    name: 'Support Starter',
    slug: 'support-starter',
    vertical: 'support',
    description:
      'Everything you need to automate tier-1 support: email triage, ticket routing, sentiment tracking, and attachment management.',
    includedCategories: ['support'],
    includedAgents: [
      'agent-inbox-triage',
      'agent-ticket-router',
      'agent-sentiment-tracker',
      'agent-attachment-archiver',
    ],
    includedWorkflows: ['wf-01', 'wf-02', 'wf-10', 'wf-26'],
    setupTimeEstimate: '30 minutes',
    kpis: ['70% faster response time', '95% ticket routing accuracy', 'Real-time sentiment alerts'],
    riskProfile: 'low',
    monthlyPrice: null,
    featured: true,
    tags: ['support', 'tickets', 'email', 'customer-success'],
    availability: 'available',
  },
  {
    id: 'pack-sales-accelerator',
    name: 'Sales Accelerator',
    slug: 'sales-accelerator',
    vertical: 'sales',
    description:
      'Close more deals with meeting prep, calendar optimization, competitive intelligence, and outbound automation.',
    includedCategories: ['sales', 'research'],
    includedAgents: ['agent-meeting-prep', 'agent-calendar-resolver', 'agent-competitor-intel'],
    includedWorkflows: ['wf-04', 'wf-24', 'wf-05'],
    setupTimeEstimate: '40 minutes',
    kpis: ['Never go unprepared', 'Zero double-bookings', 'Fresh competitive intel'],
    riskProfile: 'medium',
    monthlyPrice: 49,
    featured: true,
    tags: ['sales', 'meetings', 'competitive-intel'],
    availability: 'available',
  },
  {
    id: 'pack-research-intel',
    name: 'Research & Intel',
    slug: 'research-intel',
    vertical: 'research',
    description:
      'Automated market monitoring, competitive research, web summarization, and knowledge synthesis.',
    includedCategories: ['research'],
    includedAgents: ['agent-market-monitor', 'agent-competitor-intel', 'agent-webpage-summarizer'],
    includedWorkflows: ['wf-03', 'wf-05', 'wf-09'],
    setupTimeEstimate: '35 minutes',
    kpis: ['Daily market digests', 'Instant webpage summaries', 'Competitive tracking'],
    riskProfile: 'low',
    monthlyPrice: null,
    featured: true,
    tags: ['research', 'monitoring', 'competitive-intel'],
    availability: 'preview',
  },
  {
    id: 'pack-backoffice',
    name: 'Backoffice',
    slug: 'backoffice',
    vertical: 'ops',
    description:
      'Streamline operations with document processing, attachment archival, inbox management, and HR screening.',
    includedCategories: ['ops', 'finance'],
    includedAgents: ['agent-resume-evaluator', 'agent-attachment-archiver', 'agent-inbox-triage'],
    includedWorkflows: ['wf-25', 'wf-26', 'wf-01'],
    setupTimeEstimate: '35 minutes',
    kpis: ['Faster document processing', 'Organized file storage', 'Streamlined HR screening'],
    riskProfile: 'medium',
    monthlyPrice: 29,
    tags: ['ops', 'hr', 'documents', 'admin'],
    availability: 'preview',
  },
  {
    id: 'pack-marketing-engine',
    name: 'Marketing Engine',
    slug: 'marketing-engine',
    vertical: 'marketing',
    description:
      'Power your marketing with content research, competitive analysis, and trend monitoring.',
    includedCategories: ['marketing', 'research'],
    includedAgents: ['agent-market-monitor', 'agent-webpage-summarizer', 'agent-competitor-intel'],
    includedWorkflows: ['wf-03', 'wf-09', 'wf-05'],
    setupTimeEstimate: '30 minutes',
    kpis: ['Track industry trends', 'Monitor competitor content', 'Research on demand'],
    riskProfile: 'low',
    monthlyPrice: null,
    tags: ['marketing', 'content', 'research'],
    availability: 'preview',
  },
  {
    id: 'pack-solo-founder',
    name: 'Solo Founder',
    slug: 'solo-founder',
    vertical: 'personal',
    description:
      'Everything a solo founder needs: inbox zero, file management, research tools, and market intelligence.',
    includedCategories: ['personal', 'research'],
    includedAgents: [
      'agent-inbox-triage',
      'agent-attachment-archiver',
      'agent-webpage-summarizer',
      'agent-market-monitor',
    ],
    includedWorkflows: ['wf-01', 'wf-26', 'wf-09', 'wf-03'],
    setupTimeEstimate: '25 minutes',
    kpis: ['Inbox under control', 'Files always organized', 'Stay informed effortlessly'],
    riskProfile: 'low',
    monthlyPrice: null,
    featured: true,
    tags: ['personal', 'founder', 'productivity', 'solopreneur'],
    availability: 'preview',
  },
];

// Integrations
export const integrations: Integration[] = [
  {
    id: 'gmail',
    name: 'Gmail',
    icon: 'mail',
    category: 'communication',
    status: 'connected',
    scopes: ['gmail.readonly', 'gmail.send', 'gmail.labels'],
    requiredScopes: ['gmail.readonly', 'gmail.send', 'gmail.labels'],
    lastTestAt: '2024-03-02T10:00:00Z',
    oauthUrl: '/api/oauth/gmail',
  },
  {
    id: 'slack',
    name: 'Slack',
    icon: 'message-square',
    category: 'communication',
    status: 'connected',
    scopes: ['channels:read', 'chat:write', 'users:read'],
    requiredScopes: ['channels:read', 'chat:write', 'users:read', 'reactions:read'],
    lastTestAt: '2024-03-02T10:05:00Z',
    oauthUrl: '/api/oauth/slack',
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    icon: 'calendar',
    category: 'productivity',
    status: 'connected',
    scopes: ['calendar.readonly', 'calendar.events'],
    requiredScopes: ['calendar.readonly', 'calendar.events'],
    lastTestAt: '2024-03-02T10:10:00Z',
    oauthUrl: '/api/oauth/google-calendar',
  },
  {
    id: 'google-sheets',
    name: 'Google Sheets',
    icon: 'table',
    category: 'productivity',
    status: 'connected',
    scopes: ['spreadsheets'],
    requiredScopes: ['spreadsheets'],
    lastTestAt: '2024-03-02T10:15:00Z',
    oauthUrl: '/api/oauth/google-sheets',
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    icon: 'hard-drive',
    category: 'storage',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['drive.file', 'drive.readonly'],
    lastTestAt: null,
    oauthUrl: '/api/oauth/google-drive',
  },
  {
    id: 'notion',
    name: 'Notion',
    icon: 'file-text',
    category: 'productivity',
    status: 'connected',
    scopes: ['read_content', 'update_content', 'insert_content'],
    requiredScopes: ['read_content', 'update_content', 'insert_content'],
    lastTestAt: '2024-03-02T10:20:00Z',
    oauthUrl: '/api/oauth/notion',
  },
  {
    id: 'linear',
    name: 'Linear',
    icon: 'git-branch',
    category: 'dev',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['read', 'write', 'issues:create'],
    lastTestAt: null,
    oauthUrl: '/api/oauth/linear',
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp Business',
    icon: 'phone',
    category: 'communication',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['messages:send'],
    lastTestAt: null,
    oauthUrl: '/api/oauth/whatsapp',
  },
  {
    id: 'apify',
    name: 'Apify',
    icon: 'globe',
    category: 'dev',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['actors:run', 'datasets:read'],
    lastTestAt: null,
  },
  {
    id: 'openai',
    name: 'OpenAI',
    icon: 'brain',
    category: 'dev',
    status: 'connected',
    scopes: ['chat', 'embeddings'],
    requiredScopes: ['chat', 'embeddings'],
    lastTestAt: '2024-03-02T10:25:00Z',
  },
  {
    id: 'exa',
    name: 'Exa Search',
    icon: 'search',
    category: 'dev',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['search'],
    lastTestAt: null,
  },
  {
    id: 'serpapi',
    name: 'SerpAPI',
    icon: 'search',
    category: 'dev',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['search'],
    lastTestAt: null,
  },
  {
    id: 'trustpilot',
    name: 'Trustpilot',
    icon: 'star',
    category: 'crm',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['reviews:read'],
    lastTestAt: null,
  },
  // Merge in new integrations from catalog
  ...newIntegrations,
];

// Installed Agents
export const installedAgents: InstalledAgent[] = [
  // Demo workspace agents
  {
    id: 'demo-agent-1',
    tenantId: 'demo-workspace',
    templateId: 'agent-inbox-triage',
    status: 'active',
    installedAt: '2024-02-01T10:00:00Z',
    config: { tone: 'professional', autoReplyThreshold: 0.85 },
    hitlEnabled: true,
    lastRunAt: '2024-03-02T15:00:00Z',
    runsTotal: 2450,
    runsSuccess: 2320,
    kpiValues: { 'Response Time': 1.8, 'Deflection Rate': 78 },
  },
  {
    id: 'demo-agent-2',
    tenantId: 'demo-workspace',
    templateId: 'agent-meeting-prep',
    status: 'active',
    installedAt: '2024-02-01T11:00:00Z',
    config: { meetingTypes: ['sales', 'customer'], notifyBefore: 30 },
    hitlEnabled: false,
    lastRunAt: '2024-03-02T14:00:00Z',
    runsTotal: 180,
    runsSuccess: 175,
    kpiValues: { 'Prep Completeness': 95, 'Time Saved': 45 },
  },
  {
    id: 'demo-agent-3',
    tenantId: 'demo-workspace',
    templateId: 'agent-market-monitor',
    status: 'active',
    installedAt: '2024-02-05T09:00:00Z',
    config: {
      feeds: ['techcrunch', 'hackernews', 'producthunt'],
      keywords: ['AI', 'agents', 'automation'],
    },
    hitlEnabled: false,
    lastRunAt: '2024-03-02T10:00:00Z',
    runsTotal: 56,
    runsSuccess: 56,
    kpiValues: { 'Relevance Score': 4.5, 'Time Saved': 12 },
  },
  // Tenant ACME agents
  {
    id: 'inst-agent-1',
    tenantId: 'tenant-acme',
    templateId: 'agent-inbox-triage',
    status: 'active',
    installedAt: '2024-02-15T10:00:00Z',
    config: { tone: 'professional', autoReplyThreshold: 0.9 },
    hitlEnabled: true,
    lastRunAt: '2024-03-02T14:30:00Z',
    runsTotal: 1250,
    runsSuccess: 1180,
    kpiValues: { 'Response Time': 2.3, 'Deflection Rate': 72 },
  },
  {
    id: 'inst-agent-2',
    tenantId: 'tenant-acme',
    templateId: 'agent-ticket-router',
    status: 'active',
    installedAt: '2024-02-15T10:30:00Z',
    config: { defaultTeam: 'support', escalationThreshold: 'high' },
    hitlEnabled: false,
    lastRunAt: '2024-03-02T14:25:00Z',
    runsTotal: 890,
    runsSuccess: 875,
    kpiValues: { 'Routing Accuracy': 96, 'Time to Assignment': 1.8 },
  },
  {
    id: 'inst-agent-3',
    tenantId: 'tenant-acme',
    templateId: 'agent-market-monitor',
    status: 'active',
    installedAt: '2024-02-20T09:00:00Z',
    config: { feeds: ['techcrunch', 'hackernews'], keywords: ['AI', 'SaaS'] },
    hitlEnabled: false,
    lastRunAt: '2024-03-02T09:00:00Z',
    runsTotal: 45,
    runsSuccess: 45,
    kpiValues: { 'Relevance Score': 4.2, 'Time Saved': 8 },
  },
];

// Installed Workflows
export const installedWorkflows: InstalledWorkflow[] = [
  // Demo workspace workflows
  {
    id: 'demo-wf-1',
    tenantId: 'demo-workspace',
    templateId: 'wf-01',
    status: 'active',
    installedAt: '2024-02-01T10:00:00Z',
    config: { labels: ['urgent', 'sales', 'support', 'spam', 'newsletter'] },
    lastRunAt: '2024-03-02T15:00:00Z',
    runsTotal: 3200,
    runsSuccess: 3150,
  },
  {
    id: 'demo-wf-2',
    tenantId: 'demo-workspace',
    templateId: 'wf-04',
    status: 'active',
    installedAt: '2024-02-01T11:00:00Z',
    config: { notifyBefore: 30, platforms: ['zoom', 'google-meet'] },
    lastRunAt: '2024-03-02T14:30:00Z',
    runsTotal: 420,
    runsSuccess: 415,
  },
  {
    id: 'demo-wf-3',
    tenantId: 'demo-workspace',
    templateId: 'wf-05',
    status: 'active',
    installedAt: '2024-02-05T09:00:00Z',
    config: { slackChannel: '#market-intel' },
    lastRunAt: '2024-03-02T10:00:00Z',
    runsTotal: 56,
    runsSuccess: 56,
  },
  // Tenant ACME workflows
  {
    id: 'inst-wf-1',
    tenantId: 'tenant-acme',
    templateId: 'wf-01',
    status: 'active',
    installedAt: '2024-02-15T10:00:00Z',
    config: { labels: ['urgent', 'sales', 'support', 'spam'] },
    lastRunAt: '2024-03-02T14:30:00Z',
    runsTotal: 1250,
    runsSuccess: 1230,
  },
  {
    id: 'inst-wf-2',
    tenantId: 'tenant-acme',
    templateId: 'wf-02',
    status: 'active',
    installedAt: '2024-02-15T10:30:00Z',
    config: { dedupeWindow: 24 },
    lastRunAt: '2024-03-02T14:25:00Z',
    runsTotal: 320,
    runsSuccess: 315,
  },
  {
    id: 'inst-wf-3',
    tenantId: 'tenant-acme',
    templateId: 'wf-03',
    status: 'active',
    installedAt: '2024-02-20T09:00:00Z',
    config: { slackChannel: '#daily-digest' },
    lastRunAt: '2024-03-02T09:00:00Z',
    runsTotal: 45,
    runsSuccess: 45,
  },
];

// Approval Requests
export const approvalRequests: ApprovalRequest[] = [
  // Demo workspace approvals
  {
    id: 'demo-approval-1',
    tenantId: 'demo-workspace',
    runId: 'demo-run-100',
    agentId: 'agent-inbox-triage',
    actionType: 'send_email',
    riskLevel: 'medium',
    title: 'Send follow-up email to prospect',
    description:
      'The Inbox Triage agent wants to send a follow-up email to a prospect who inquired about enterprise features.',
    payloadPreview: {
      to: 'enterprise@company.com',
      subject: 'Re: Enterprise features inquiry',
      body: 'Thank you for your interest in our enterprise plan. I would be happy to schedule a call to discuss your specific needs...',
    },
    context: {
      inputs: {
        email_content: 'We are evaluating AI agent platforms for our team...',
        sender_info: { email: 'enterprise@company.com', name: 'Sarah Chen' },
      },
      sources: ['enterprise-pricing', 'case-studies'],
      previousMessages: ['Initial inquiry received yesterday'],
    },
    status: 'pending',
    requestedAt: '2024-03-02T15:10:00Z',
  },
  {
    id: 'demo-approval-2',
    tenantId: 'demo-workspace',
    runId: 'demo-run-101',
    agentId: 'agent-meeting-prep',
    actionType: 'update_calendar',
    riskLevel: 'low',
    title: 'Add meeting prep notes to calendar event',
    description:
      'The Meeting Prep agent wants to add preparation notes and talking points to an upcoming customer call.',
    payloadPreview: {
      action: 'update_event',
      eventId: 'cal-demo-1',
      notes: 'Talking points: Q4 roadmap, Integration options, Pricing discussion',
    },
    context: {
      inputs: { meeting_title: 'Customer Success Call - Acme Corp' },
      sources: ['crm', 'previous-meetings'],
    },
    status: 'pending',
    requestedAt: '2024-03-02T15:15:00Z',
  },
  // Tenant ACME approvals
  {
    id: 'approval-1',
    tenantId: 'tenant-acme',
    runId: 'run-123',
    agentId: 'agent-inbox-triage',
    actionType: 'send_email',
    riskLevel: 'medium',
    title: 'Send auto-reply to customer inquiry',
    description:
      'The Inbox Triage agent wants to send an automated response to a customer asking about pricing.',
    payloadPreview: {
      to: 'customer@example.com',
      subject: 'Re: Pricing inquiry',
      body: 'Thank you for your interest in our products. Our pricing starts at $29/month for the Starter plan...',
    },
    context: {
      inputs: {
        email_content: 'Hi, I wanted to know about your pricing...',
        sender_info: { email: 'customer@example.com', name: 'John Doe' },
      },
      sources: ['pricing-page', 'faq'],
      previousMessages: ['Initial inquiry received at 2:30 PM'],
    },
    status: 'pending',
    requestedAt: '2024-03-02T14:35:00Z',
  },
  {
    id: 'approval-2',
    tenantId: 'tenant-acme',
    runId: 'run-124',
    agentId: 'agent-calendar-resolver',
    actionType: 'update_crm',
    riskLevel: 'high',
    title: 'Reschedule conflicting meetings',
    description: 'The Calendar Resolver wants to reschedule 2 meetings to resolve a conflict.',
    payloadPreview: {
      action: 'reschedule',
      meetings: [
        { id: 'meet-1', originalTime: '2024-03-03T10:00', newTime: '2024-03-03T11:00' },
        { id: 'meet-2', originalTime: '2024-03-03T10:30', newTime: '2024-03-03T14:00' },
      ],
    },
    context: {
      inputs: { calendar_events: ['meet-1', 'meet-2', 'meet-3'] },
      sources: ['google-calendar'],
    },
    status: 'pending',
    requestedAt: '2024-03-02T14:40:00Z',
  },
  {
    id: 'approval-3',
    tenantId: 'tenant-acme',
    runId: 'run-125',
    agentId: 'agent-ticket-router',
    actionType: 'create_ticket',
    riskLevel: 'low',
    title: 'Create P1 ticket for outage report',
    description: 'Route urgent outage report to platform team as P1 ticket.',
    payloadPreview: {
      title: '[URGENT] Service outage reported',
      priority: 'P1',
      team: 'platform',
      labels: ['outage', 'urgent'],
    },
    context: {
      inputs: {
        ticket_subject: 'Service is down!',
        ticket_body: 'We cannot access the dashboard since 2pm...',
      },
      sources: ['support-email'],
    },
    status: 'approved',
    requestedAt: '2024-03-02T14:20:00Z',
    decidedAt: '2024-03-02T14:22:00Z',
    decidedBy: 'admin@acme.com',
  },
];

// Execution Runs
export const executionRuns: ExecutionRun[] = [
  // Demo workspace runs
  {
    id: 'demo-exec-1',
    tenantId: 'demo-workspace',
    agentId: 'agent-inbox-triage',
    workflowId: 'wf-01',
    status: 'success',
    startedAt: '2024-03-02T15:00:00Z',
    completedAt: '2024-03-02T15:00:02Z',
    durationMs: 2100,
    costEstimate: 0.0021,
    tokensUsed: 1250,
    logs: [
      '[15:00:00] Triggered by new email from prospect@startup.io',
      '[15:00:00] Parsing email content...',
      '[15:00:01] Classifying email type: sales inquiry',
      '[15:00:01] Generating response draft...',
      '[15:00:02] Run completed successfully',
    ],
    timeline: [
      {
        id: 's1',
        type: 'tool_call',
        name: 'Email Received',
        status: 'success',
        startedAt: '2024-03-02T15:00:00Z',
        durationMs: 50,
      },
      {
        id: 's2',
        type: 'tool_call',
        name: 'Parse Email',
        status: 'success',
        startedAt: '2024-03-02T15:00:00Z',
        durationMs: 150,
      },
      {
        id: 's3',
        type: 'agent_invoke',
        name: 'Classify & Draft',
        status: 'success',
        startedAt: '2024-03-02T15:00:00Z',
        durationMs: 1600,
        tokenUsage: 1250,
        cost: 0.0021,
      },
      {
        id: 's4',
        type: 'tool_call',
        name: 'Return Result',
        status: 'success',
        startedAt: '2024-03-02T15:00:02Z',
        durationMs: 50,
      },
    ],
    triggeredBy: 'webhook',
    tags: ['email', 'triage', 'auto-response'],
  },
  {
    id: 'demo-exec-2',
    tenantId: 'demo-workspace',
    agentId: 'agent-meeting-prep',
    workflowId: 'wf-04',
    status: 'success',
    startedAt: '2024-03-02T14:00:00Z',
    completedAt: '2024-03-02T14:00:05Z',
    durationMs: 4800,
    costEstimate: 0.0035,
    tokensUsed: 1850,
    logs: [
      '[14:00:00] Triggered by calendar event starting in 30 min',
      '[14:00:01] Fetching attendee information from CRM...',
      '[14:00:02] Gathering context from previous meetings...',
      '[14:00:03] Generating prep brief...',
      '[14:00:05] Prep notes sent to Slack',
    ],
    timeline: [
      {
        id: 's1',
        type: 'tool_call',
        name: 'Calendar Event',
        status: 'success',
        startedAt: '2024-03-02T14:00:00Z',
        durationMs: 100,
      },
      {
        id: 's2',
        type: 'tool_call',
        name: 'CRM Lookup',
        status: 'success',
        startedAt: '2024-03-02T14:00:00Z',
        durationMs: 800,
      },
      {
        id: 's3',
        type: 'tool_call',
        name: 'Previous Meetings',
        status: 'success',
        startedAt: '2024-03-02T14:00:01Z',
        durationMs: 600,
      },
      {
        id: 's4',
        type: 'agent_invoke',
        name: 'Generate Brief',
        status: 'success',
        startedAt: '2024-03-02T14:00:02Z',
        durationMs: 2800,
        tokenUsage: 1850,
        cost: 0.0035,
      },
      {
        id: 's5',
        type: 'tool_call',
        name: 'Post to Slack',
        status: 'success',
        startedAt: '2024-03-02T14:00:05Z',
        durationMs: 200,
      },
    ],
    triggeredBy: 'cron',
    tags: ['meeting', 'prep', 'slack'],
  },
  {
    id: 'demo-exec-3',
    tenantId: 'demo-workspace',
    agentId: 'agent-market-monitor',
    workflowId: 'wf-05',
    status: 'failed',
    startedAt: '2024-03-02T10:00:00Z',
    completedAt: '2024-03-02T10:00:08Z',
    durationMs: 8200,
    costEstimate: 0.0012,
    tokensUsed: 650,
    logs: [
      '[10:00:00] Triggered by daily cron',
      '[10:00:01] Fetching RSS feeds...',
      '[10:00:05] Error: Rate limit exceeded for HackerNews API',
      '[10:00:08] Run failed after 3 retries',
    ],
    timeline: [
      {
        id: 's1',
        type: 'tool_call',
        name: 'Daily Cron',
        status: 'success',
        startedAt: '2024-03-02T10:00:00Z',
        durationMs: 50,
      },
      {
        id: 's2',
        type: 'tool_call',
        name: 'Fetch Feeds',
        status: 'error',
        startedAt: '2024-03-02T10:00:00Z',
        durationMs: 8000,
        error: 'Rate limit exceeded',
      },
    ],
    triggeredBy: 'cron',
    tags: ['market', 'monitor', 'error'],
  },
  // Tenant ACME runs
  {
    id: 'exec-1',
    tenantId: 'tenant-acme',
    agentId: 'agent-inbox-triage',
    workflowId: 'wf-01',
    status: 'success',
    startedAt: '2024-03-02T14:30:00Z',
    completedAt: '2024-03-02T14:30:03Z',
    durationMs: 2850,
    costEstimate: 0.0024,
    tokensUsed: 1420,
    logs: [
      '[14:30:00] Triggered by new email from customer@example.com',
      '[14:30:01] Parsing email content...',
      '[14:30:01] Classifying email type: inquiry',
      '[14:30:02] Generating draft response...',
      '[14:30:02] HITL check: requires approval for send_email',
      '[14:30:03] Run completed - awaiting approval',
    ],
    timeline: [
      {
        id: 's1',
        type: 'tool_call',
        name: 'Email Received',
        status: 'success',
        startedAt: '2024-03-02T14:30:00Z',
        durationMs: 50,
      },
      {
        id: 's2',
        type: 'tool_call',
        name: 'Parse Email',
        status: 'success',
        startedAt: '2024-03-02T14:30:00Z',
        durationMs: 200,
      },
      {
        id: 's3',
        type: 'agent_invoke',
        name: 'Classify & Draft',
        status: 'success',
        startedAt: '2024-03-02T14:30:01Z',
        durationMs: 1800,
        tokenUsage: 1420,
        cost: 0.0024,
      },
      {
        id: 's4',
        type: 'approval',
        name: 'HITL Check',
        status: 'pending_approval',
        startedAt: '2024-03-02T14:30:02Z',
        durationMs: 100,
      },
      {
        id: 's5',
        type: 'tool_call',
        name: 'Return Result',
        status: 'success',
        startedAt: '2024-03-02T14:30:03Z',
        durationMs: 50,
      },
    ],
    triggeredBy: 'webhook',
    tags: ['email', 'triage', 'pending-approval'],
  },
  {
    id: 'exec-2',
    tenantId: 'tenant-acme',
    agentId: 'agent-ticket-router',
    workflowId: 'wf-02',
    status: 'success',
    startedAt: '2024-03-02T14:25:00Z',
    completedAt: '2024-03-02T14:25:02Z',
    durationMs: 1850,
    costEstimate: 0.0018,
    tokensUsed: 980,
    logs: [
      '[14:25:00] Triggered by Slack reaction',
      '[14:25:00] Checking dedupe ledger...',
      '[14:25:01] No duplicate found, proceeding',
      '[14:25:01] Classifying ticket urgency: high',
      '[14:25:02] Created Linear ticket LIN-456',
      '[14:25:02] Run completed successfully',
    ],
    timeline: [
      {
        id: 's1',
        type: 'tool_call',
        name: 'Slack Event',
        status: 'success',
        startedAt: '2024-03-02T14:25:00Z',
        durationMs: 30,
      },
      {
        id: 's2',
        type: 'tool_call',
        name: 'Dedupe Check',
        status: 'success',
        startedAt: '2024-03-02T14:25:00Z',
        durationMs: 300,
      },
      {
        id: 's3',
        type: 'agent_invoke',
        name: 'Classify Ticket',
        status: 'success',
        startedAt: '2024-03-02T14:25:01Z',
        durationMs: 1200,
        tokenUsage: 980,
        cost: 0.0018,
      },
      {
        id: 's4',
        type: 'tool_call',
        name: 'Create Linear Ticket',
        status: 'success',
        startedAt: '2024-03-02T14:25:02Z',
        durationMs: 320,
      },
    ],
    triggeredBy: 'webhook',
    tags: ['slack', 'linear', 'ticket'],
  },
  {
    id: 'exec-3',
    tenantId: 'tenant-acme',
    agentId: 'agent-market-monitor',
    workflowId: 'wf-03',
    status: 'success',
    startedAt: '2024-03-02T09:00:00Z',
    completedAt: '2024-03-02T09:02:30Z',
    durationMs: 150000,
    costEstimate: 0.0156,
    tokensUsed: 8500,
    logs: [
      '[09:00:00] Daily digest triggered',
      '[09:00:05] Fetching RSS feeds...',
      '[09:00:30] Retrieved 45 new items',
      '[09:00:35] Checking dedupe ledger...',
      '[09:00:40] 12 new unique items to process',
      '[09:01:00] Summarizing with AI...',
      '[09:02:00] Posting digest to #daily-digest',
      '[09:02:30] Run completed successfully',
    ],
    timeline: [
      {
        id: 's1',
        type: 'tool_call',
        name: 'Cron Trigger',
        status: 'success',
        startedAt: '2024-03-02T09:00:00Z',
        durationMs: 10,
      },
      {
        id: 's2',
        type: 'tool_call',
        name: 'Fetch RSS',
        status: 'success',
        startedAt: '2024-03-02T09:00:05Z',
        durationMs: 25000,
      },
      {
        id: 's3',
        type: 'tool_call',
        name: 'Dedupe',
        status: 'success',
        startedAt: '2024-03-02T09:00:35Z',
        durationMs: 5000,
      },
      {
        id: 's4',
        type: 'agent_invoke',
        name: 'Summarize',
        status: 'success',
        startedAt: '2024-03-02T09:01:00Z',
        durationMs: 60000,
        tokenUsage: 8500,
        cost: 0.0156,
      },
      {
        id: 's5',
        type: 'tool_call',
        name: 'Post to Slack',
        status: 'success',
        startedAt: '2024-03-02T09:02:00Z',
        durationMs: 30000,
      },
    ],
    triggeredBy: 'cron',
    tags: ['digest', 'rss', 'slack'],
  },
  {
    id: 'exec-4',
    tenantId: 'tenant-acme',
    agentId: 'agent-inbox-triage',
    status: 'failed',
    startedAt: '2024-03-02T13:15:00Z',
    completedAt: '2024-03-02T13:15:05Z',
    durationMs: 5000,
    costEstimate: 0.0008,
    tokensUsed: 350,
    logs: [
      '[13:15:00] Triggered by new email',
      '[13:15:01] Parsing email content...',
      '[13:15:02] Error: Gmail API rate limit exceeded',
      '[13:15:03] Retry 1/3...',
      '[13:15:04] Error: Gmail API rate limit exceeded',
      '[13:15:05] Max retries exceeded. Run failed.',
    ],
    timeline: [
      {
        id: 's1',
        type: 'tool_call',
        name: 'Email Received',
        status: 'success',
        startedAt: '2024-03-02T13:15:00Z',
        durationMs: 50,
      },
      {
        id: 's2',
        type: 'tool_call',
        name: 'Parse Email',
        status: 'failed',
        startedAt: '2024-03-02T13:15:01Z',
        durationMs: 4950,
        error: 'Gmail API rate limit exceeded',
      },
    ],
    triggeredBy: 'webhook',
    tags: ['email', 'error', 'rate-limit'],
  },
  {
    id: 'exec-5',
    tenantId: 'tenant-acme',
    agentId: 'agent-ticket-router',
    status: 'running',
    startedAt: '2024-03-02T14:45:00Z',
    durationMs: 0,
    costEstimate: 0,
    tokensUsed: 0,
    logs: ['[14:45:00] Triggered by Slack reaction', '[14:45:01] Processing...'],
    timeline: [
      {
        id: 's1',
        type: 'tool_call',
        name: 'Slack Event',
        status: 'success',
        startedAt: '2024-03-02T14:45:00Z',
        durationMs: 30,
      },
      {
        id: 's2',
        type: 'tool_call',
        name: 'Dedupe Check',
        status: 'running',
        startedAt: '2024-03-02T14:45:01Z',
      },
    ],
    triggeredBy: 'webhook',
    tags: ['slack', 'running'],
  },
];

// Security
export const securityFindings: SecurityFinding[] = [
  {
    id: 'finding-1',
    tenantId: 'tenant-acme',
    severity: 'high',
    title: 'Webhook endpoint without authentication',
    description:
      'The workflow wf-02 has a public webhook endpoint that accepts requests without API key validation.',
    remediation:
      'Enable webhook authentication in workflow settings or use the command center pattern.',
    detectedAt: '2024-03-01T10:00:00Z',
    category: 'webhook',
  },
  {
    id: 'finding-2',
    tenantId: 'tenant-acme',
    severity: 'medium',
    title: 'Agent without HITL for high-risk action',
    description: 'agent-calendar-resolver can reschedule meetings without human approval.',
    remediation: 'Enable Human-in-the-loop for this agent in settings.',
    detectedAt: '2024-03-01T10:00:00Z',
    category: 'hitl',
  },
  {
    id: 'finding-3',
    tenantId: 'tenant-acme',
    severity: 'low',
    title: 'Log retention exceeds recommended period',
    description: 'Logs are retained for 30 days. Consider reducing to 7 days for PII compliance.',
    remediation: 'Adjust log retention in Settings > Security.',
    detectedAt: '2024-03-01T10:00:00Z',
    category: 'pii',
  },
];

export const securityPolicies: SecurityPolicy[] = [
  {
    id: 'policy-1',
    tenantId: 'tenant-acme',
    name: 'Block unauthenticated webhooks',
    description: 'All webhook endpoints must require authentication via API key or signature.',
    enabled: false,
    category: 'auth',
  },
  {
    id: 'policy-2',
    tenantId: 'tenant-acme',
    name: 'Require HITL for high-risk actions',
    description: 'Actions classified as high-risk must go through human approval.',
    enabled: true,
    category: 'hitl',
  },
  {
    id: 'policy-3',
    tenantId: 'tenant-acme',
    name: 'Mask PII in logs',
    description: 'Automatically redact personal identifiable information in execution logs.',
    enabled: true,
    category: 'logging',
  },
  {
    id: 'policy-4',
    tenantId: 'tenant-acme',
    name: 'Encrypt secrets at rest',
    description: 'All stored secrets are encrypted using AES-256.',
    enabled: true,
    category: 'data',
  },
];

// Members
export const tenantMembers: TenantMember[] = [
  {
    id: 'member-1',
    tenantId: 'tenant-acme',
    email: 'admin@acme.com',
    name: 'Admin User',
    role: 'owner',
    joinedAt: '2024-01-15T10:00:00Z',
    lastActiveAt: '2024-03-02T14:00:00Z',
  },
  {
    id: 'member-2',
    tenantId: 'tenant-acme',
    email: 'ops@acme.com',
    name: 'Ops Manager',
    role: 'admin',
    joinedAt: '2024-01-20T09:00:00Z',
    lastActiveAt: '2024-03-02T12:00:00Z',
  },
  {
    id: 'member-3',
    tenantId: 'tenant-acme',
    email: 'viewer@acme.com',
    name: 'View Only',
    role: 'viewer',
    joinedAt: '2024-02-01T14:00:00Z',
    lastActiveAt: '2024-03-01T10:00:00Z',
  },
  {
    id: 'member-4',
    tenantId: 'tenant-fisio',
    email: 'ops@fisio.test',
    name: 'Fisio Operator',
    role: 'admin',
    joinedAt: '2024-03-01T09:00:00Z',
    lastActiveAt: '2024-03-04T11:00:00Z',
  },
];

// Invoices
export const invoices: Invoice[] = [
  {
    id: 'inv-1',
    tenantId: 'tenant-acme',
    date: '2024-03-01',
    amount: 99,
    status: 'paid',
    currency: 'usd',
    items: [{ description: 'Pro Plan - March 2024', amount: 99 }],
  },
  {
    id: 'inv-2',
    tenantId: 'tenant-acme',
    date: '2024-02-01',
    amount: 99,
    status: 'paid',
    currency: 'usd',
    items: [{ description: 'Pro Plan - February 2024', amount: 99 }],
  },
];

// Dashboard Metrics
export const dashboardMetrics: DashboardMetrics = {
  tenantId: 'tenant-acme',
  period: 'week',
  runsTotal: 2185,
  runsSuccess: 2050,
  runsFailed: 135,
  avgLatencyMs: 2450,
  totalCost: 42.5,
  topAgents: [
    { agentId: 'agent-inbox-triage', runs: 1250 },
    { agentId: 'agent-ticket-router', runs: 890 },
    { agentId: 'agent-market-monitor', runs: 45 },
  ],
  topWorkflows: [
    { workflowId: 'wf-01', runs: 1250 },
    { workflowId: 'wf-02', runs: 890 },
    { workflowId: 'wf-03', runs: 45 },
  ],
  costByDay: [
    { date: '2024-02-25', cost: 5.2 },
    { date: '2024-02-26', cost: 6.1 },
    { date: '2024-02-27', cost: 5.8 },
    { date: '2024-02-28', cost: 7.2 },
    { date: '2024-02-29', cost: 6.5 },
    { date: '2024-03-01', cost: 5.9 },
    { date: '2024-03-02', cost: 5.8 },
  ],
  runsByDay: [
    { date: '2024-02-25', count: 285 },
    { date: '2024-02-26', count: 320 },
    { date: '2024-02-27', count: 295 },
    { date: '2024-02-28', count: 340 },
    { date: '2024-02-29', count: 310 },
    { date: '2024-03-01', count: 325 },
    { date: '2024-03-02', count: 310 },
  ],
  errorsByType: [
    { type: 'Rate Limit', count: 45 },
    { type: 'Timeout', count: 32 },
    { type: 'Auth Error', count: 28 },
    { type: 'Validation', count: 20 },
    { type: 'Other', count: 10 },
  ],
};

// n8n Connection
export const n8nConnections: N8nConnection[] = [
  {
    tenantId: 'tenant-acme',
    baseUrl: 'https://n8n.acme.com',
    apiKeySet: true,
    lastTestAt: '2024-03-02T10:00:00Z',
    lastTestStatus: 'success',
    executionCount: 2185,
  },
  {
    tenantId: 'demo-workspace',
    baseUrl: 'https://n8n.demo.agentmou.io',
    apiKeySet: true,
    lastTestAt: '2024-03-02T10:00:00Z',
    lastTestStatus: 'success',
    executionCount: 1234,
  },
];

// Aliased exports for pages
export const mockTenants = tenants;
export const mockAgents = agentTemplates;
export const mockWorkflows = workflowTemplates;
export const mockPacks = packTemplates;
export const mockIntegrations = integrations;
export const mockInstalledAgents = installedAgents;
export const mockInstalledWorkflows = installedWorkflows;
export const mockApprovalRequests = approvalRequests;
export const mockRuns = executionRuns;
export const mockSecurityFindings = securityFindings;
export const mockSecurityPolicies = securityPolicies;
export const mockTeamMembers = tenantMembers;
export const mockInvoices = invoices;
export const mockMetrics = dashboardMetrics;
export const mockN8nConnections = n8nConnections;

// Additional mock data for security page
export const mockSecrets = [
  {
    id: 'secret-1',
    key: 'OPENAI_API_KEY',
    value: 'sk-proj-xxxx...xxxx',
    createdAt: '2024-01-15T10:00:00Z',
    lastRotated: '2024-02-28T10:00:00Z',
    usedBy: ['Email Classifier', 'Content Writer'],
  },
  {
    id: 'secret-2',
    key: 'SLACK_BOT_TOKEN',
    value: 'xoxb-xxxx...xxxx',
    createdAt: '2024-01-15T10:00:00Z',
    lastRotated: '2024-02-15T10:00:00Z',
    usedBy: ['Slack Notifier', 'Support Triage'],
  },
  {
    id: 'secret-3',
    key: 'LINEAR_API_KEY',
    value: 'lin_api_xxxx...xxxx',
    createdAt: '2024-01-20T10:00:00Z',
    lastRotated: '2024-02-20T10:00:00Z',
    usedBy: ['Linear Sync'],
  },
  {
    id: 'secret-4',
    key: 'STRIPE_SECRET_KEY',
    value: 'sk_live_xxxx...xxxx',
    createdAt: '2024-02-01T10:00:00Z',
    lastRotated: '2024-03-01T10:00:00Z',
    usedBy: ['Invoice Processor'],
  },
];

export const mockAuditEvents = [
  {
    id: 'audit-1',
    timestamp: '2024-03-02T14:30:00Z',
    action: 'Agent installed',
    actor: 'john@acme.com',
    category: 'agent',
    details: 'Installed "Lead Qualifier" agent',
  },
  {
    id: 'audit-2',
    timestamp: '2024-03-02T14:15:00Z',
    action: 'Workflow enabled',
    actor: 'john@acme.com',
    category: 'workflow',
    details: 'Enabled "Slack to Linear" workflow',
  },
  {
    id: 'audit-3',
    timestamp: '2024-03-02T13:45:00Z',
    action: 'Secret rotated',
    actor: 'system',
    category: 'security',
    details: 'Auto-rotated OPENAI_API_KEY',
  },
  {
    id: 'audit-4',
    timestamp: '2024-03-02T12:00:00Z',
    action: 'Member invited',
    actor: 'john@acme.com',
    category: 'security',
    details: 'Invited sarah@acme.com as Editor',
  },
  {
    id: 'audit-5',
    timestamp: '2024-03-02T11:30:00Z',
    action: 'Approval granted',
    actor: 'john@acme.com',
    category: 'agent',
    details: 'Approved send_email action for Lead Qualifier',
  },
  {
    id: 'audit-6',
    timestamp: '2024-03-02T10:00:00Z',
    action: 'Plan upgraded',
    actor: 'john@acme.com',
    category: 'billing',
    details: 'Upgraded from Starter to Pro plan',
  },
];

export const mockBillingInfo = {
  plan: 'pro',
  monthlySpend: 149.0,
  agentsInstalled: 8,
  runsThisMonth: 12500,
};
