import type { AgentTemplate } from '../types'

// Operations, Finance, HR, and IT agents
export const opsFinanceAgentTemplates: AgentTemplate[] = [
  // Finance & Collections
  {
    id: 'agent-collections-nudger',
    name: 'Collections Nudger',
    outcome: 'Improve cash flow with automated collection follow-ups',
    domain: 'finance',
    description: 'Tracks overdue invoices and sends intelligent, escalating reminders to encourage timely payment.',
    inputs: ['invoice_data', 'payment_history', 'customer_context'],
    outputs: ['nudge_sent', 'status_update', 'escalation_flag'],
    requiredIntegrations: ['gmail', 'google-sheets'],
    workflows: ['wf-plan-finance-collections'],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Collection Rate', description: 'Overdue invoices collected' },
      { name: 'Days to Payment', description: 'Average time to collection' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming Q3',
    catalogGroup: 'finance',
    family: 'finance',
    tags: ['collections', 'invoicing', 'finance', 'cash-flow'],
    visibility: 'public',
  },
  {
    id: 'agent-invoice-expense-parser',
    name: 'Invoice & Expense Parser',
    outcome: 'Extract structured data from invoices and receipts',
    domain: 'finance',
    description: 'Parses invoices and expense receipts using AI to extract amounts, dates, vendors, and line items.',
    inputs: ['document', 'extraction_schema'],
    outputs: ['structured_data', 'confidence_scores', 'validation_flags'],
    requiredIntegrations: ['gmail', 'google-drive', 'openai'],
    workflows: ['wf-plan-pdf-to-structured-data'],
    riskLevel: 'low',
    hitl: 'recommended',
    kpis: [
      { name: 'Extraction Accuracy', description: 'Field accuracy rate' },
      { name: 'Processing Speed', description: 'Documents per hour' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming Q3',
    catalogGroup: 'finance',
    family: 'finance',
    tags: ['invoices', 'expenses', 'parsing', 'finance'],
    visibility: 'public',
  },
  {
    id: 'agent-cash-aging-snapshot',
    name: 'Cash & Aging Snapshot',
    outcome: 'Weekly cash position and aging analysis',
    domain: 'finance',
    description: 'Generates weekly reports on cash position, accounts receivable aging, and cash flow projections.',
    inputs: ['financial_data', 'report_config'],
    outputs: ['cash_report', 'aging_analysis', 'projections'],
    requiredIntegrations: ['google-sheets', 'slack'],
    workflows: ['wf-plan-finance-collections'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Report Accuracy', description: 'Data reconciliation rate' },
      { name: 'Forecast Accuracy', description: 'Projection vs actual' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 30,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming Q3',
    catalogGroup: 'finance',
    family: 'finance',
    tags: ['cash-flow', 'aging', 'reporting', 'finance'],
    visibility: 'public',
  },
  
  // Operations & IT
  {
    id: 'agent-internal-request-router',
    name: 'Internal Request Router',
    outcome: 'Route internal team requests to the right handler',
    domain: 'ops',
    description: 'Classifies internal requests (IT, facilities, HR) and routes to appropriate team with SLA tracking.',
    inputs: ['request_content', 'requester_info', 'request_type'],
    outputs: ['routed_destination', 'sla', 'ticket_created'],
    requiredIntegrations: ['slack', 'linear'],
    workflows: ['wf-plan-internal-ops-router'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Routing Accuracy', description: 'Correct team assignment' },
      { name: 'Response Time', description: 'Time to first response' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 20,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming Q2',
    catalogGroup: 'ops',
    family: 'ops',
    tags: ['routing', 'internal', 'it', 'operations'],
    visibility: 'public',
    featured: true,
  },
  {
    id: 'agent-employee-onboarding-orchestrator',
    name: 'Employee Onboarding Orchestrator',
    outcome: 'Automate new hire onboarding tasks',
    domain: 'ops',
    description: 'Coordinates new employee onboarding by triggering account setup, equipment requests, and training assignments.',
    inputs: ['new_hire_data', 'role_config', 'start_date'],
    outputs: ['tasks_created', 'accounts_requested', 'training_assigned'],
    requiredIntegrations: ['slack', 'gmail', 'google-sheets'],
    workflows: ['wf-plan-hr-hiring-pipeline'],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Onboarding Completion', description: 'Tasks completed on time' },
      { name: 'Time to Productivity', description: 'Days to full setup' },
    ],
    complexity: 'L',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 45,
    monthlyPrice: 49,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming Q3',
    catalogGroup: 'ops',
    family: 'hr-hiring',
    tags: ['onboarding', 'hr', 'operations'],
    visibility: 'public',
  },
  {
    id: 'agent-incident-runbook-assistant',
    name: 'Incident Runbook Assistant',
    outcome: 'Guide teams through incident response procedures',
    domain: 'ops',
    description: 'Provides step-by-step guidance during incidents, tracking progress and logging decisions.',
    inputs: ['incident_type', 'severity', 'affected_systems'],
    outputs: ['runbook_steps', 'progress_log', 'escalation_triggers'],
    requiredIntegrations: ['slack', 'notion'],
    workflows: ['wf-plan-internal-ops-router'],
    riskLevel: 'medium',
    hitl: 'required',
    kpis: [
      { name: 'MTTR', description: 'Mean time to resolution' },
      { name: 'Runbook Adherence', description: 'Steps followed correctly' },
    ],
    complexity: 'L',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 45,
    monthlyPrice: 79,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming Q3',
    catalogGroup: 'ops',
    family: 'devops',
    tags: ['incidents', 'runbooks', 'devops', 'it'],
    visibility: 'public',
  },
  {
    id: 'agent-secrets-access-auditor',
    name: 'Secrets & Access Auditor',
    outcome: 'Monitor and audit access to sensitive resources',
    domain: 'ops',
    description: 'Tracks access to secrets, credentials, and sensitive systems with anomaly detection.',
    inputs: ['access_logs', 'policy_rules', 'alert_thresholds'],
    outputs: ['audit_report', 'anomalies', 'compliance_status'],
    requiredIntegrations: ['google-sheets'],
    workflows: ['wf-plan-security-scan'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Coverage', description: 'Resources monitored' },
      { name: 'Anomaly Detection', description: 'Issues identified' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 30,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming Q3',
    catalogGroup: 'ops',
    family: 'governance-fleetops',
    tags: ['security', 'audit', 'access', 'compliance'],
    visibility: 'public',
  },
  
  // HR & Hiring
  {
    id: 'agent-candidate-pipeline-assistant',
    name: 'Candidate Pipeline Assistant',
    outcome: 'Track candidates and automate hiring workflow',
    domain: 'ops',
    description: 'Manages candidate tracking through hiring stages with automated status updates and reminders.',
    inputs: ['candidate_data', 'pipeline_stages', 'hiring_team'],
    outputs: ['status_updates', 'next_actions', 'pipeline_metrics'],
    requiredIntegrations: ['gmail', 'google-sheets', 'slack'],
    workflows: ['wf-plan-hr-hiring-pipeline'],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Pipeline Velocity', description: 'Days to hire' },
      { name: 'Drop-off Rate', description: 'Candidates lost in process' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 30,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming Q3',
    catalogGroup: 'ops',
    family: 'hr-hiring',
    tags: ['hiring', 'candidates', 'hr', 'pipeline'],
    visibility: 'public',
  },
  {
    id: 'agent-interview-coordinator',
    name: 'Interview Coordinator',
    outcome: 'Automate interview scheduling and logistics',
    domain: 'ops',
    description: 'Coordinates interview scheduling, sends calendar invites, and manages interviewer assignments.',
    inputs: ['candidate_info', 'interviewer_pool', 'availability'],
    outputs: ['interview_scheduled', 'calendar_invites', 'prep_materials'],
    requiredIntegrations: ['google-calendar', 'gmail', 'slack'],
    workflows: ['wf-plan-hr-hiring-pipeline'],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Scheduling Speed', description: 'Hours to schedule' },
      { name: 'Reschedule Rate', description: 'Interviews rescheduled' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming Q3',
    catalogGroup: 'ops',
    family: 'hr-hiring',
    tags: ['interviews', 'scheduling', 'hr', 'hiring'],
    visibility: 'public',
  },
  
  // Inventory & Ecommerce
  {
    id: 'agent-ai-inventory-tracker',
    name: 'AI Inventory Tracker',
    outcome: 'Monitor inventory levels and predict stockouts',
    domain: 'ops',
    description: 'Tracks inventory across locations, predicts stockouts, and alerts when reorder is needed.',
    inputs: ['inventory_data', 'sales_history', 'lead_times'],
    outputs: ['stock_alerts', 'reorder_recommendations', 'forecast'],
    requiredIntegrations: ['google-sheets', 'slack'],
    workflows: ['wf-plan-ai-inventory-retention'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Stockout Prevention', description: 'Stockouts avoided' },
      { name: 'Forecast Accuracy', description: 'Prediction vs actual' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 30,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming Q3',
    catalogGroup: 'ops',
    family: 'ecommerce',
    tags: ['inventory', 'ecommerce', 'forecasting', 'operations'],
    visibility: 'public',
  },
  {
    id: 'agent-retention-consent-guard',
    name: 'Retention & Consent Guard',
    outcome: 'Enforce data retention policies automatically',
    domain: 'ops',
    description: 'Monitors data retention compliance, tracks consent status, and triggers cleanup workflows.',
    inputs: ['data_inventory', 'retention_policies', 'consent_records'],
    outputs: ['compliance_report', 'cleanup_actions', 'consent_status'],
    requiredIntegrations: ['google-sheets'],
    workflows: ['wf-plan-ai-inventory-retention'],
    riskLevel: 'medium',
    hitl: 'required',
    kpis: [
      { name: 'Policy Compliance', description: 'Data within policy' },
      { name: 'Consent Coverage', description: 'Records with valid consent' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 35,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming Q3',
    catalogGroup: 'ops',
    family: 'governance-fleetops',
    tags: ['retention', 'consent', 'compliance', 'gdpr'],
    visibility: 'public',
  },
  {
    id: 'agent-order-support-assistant',
    name: 'Order Support Assistant',
    outcome: 'Handle order inquiries with automated lookups',
    domain: 'support',
    description: 'Responds to order status inquiries, processes simple changes, and escalates complex issues.',
    inputs: ['customer_inquiry', 'order_data', 'policy_rules'],
    outputs: ['status_response', 'action_taken', 'escalation_flag'],
    requiredIntegrations: ['gmail', 'google-sheets', 'slack'],
    workflows: ['wf-plan-order-support-ops'],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Resolution Rate', description: 'Inquiries resolved' },
      { name: 'Response Time', description: 'Time to answer' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming Q3',
    catalogGroup: 'support',
    family: 'ecommerce',
    tags: ['orders', 'ecommerce', 'support', 'customer-service'],
    visibility: 'public',
  },
  {
    id: 'agent-stock-alert-monitor',
    name: 'Stock Alert Monitor',
    outcome: 'Real-time alerts on inventory changes',
    domain: 'ops',
    description: 'Monitors stock levels in real-time and sends alerts when thresholds are crossed.',
    inputs: ['inventory_feed', 'alert_thresholds', 'notification_config'],
    outputs: ['alerts_sent', 'threshold_status', 'trend_data'],
    requiredIntegrations: ['google-sheets', 'slack'],
    workflows: ['wf-plan-ai-inventory-retention'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Alert Accuracy', description: 'Relevant alerts' },
      { name: 'Alert Speed', description: 'Time to notification' },
    ],
    complexity: 'S',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 15,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming Q3',
    catalogGroup: 'ops',
    family: 'ecommerce',
    tags: ['inventory', 'alerts', 'monitoring', 'ecommerce'],
    visibility: 'public',
  },
  
  // Education & Learning
  {
    id: 'agent-study-plan-builder',
    name: 'Study Plan Builder',
    outcome: 'Create personalized study plans with AI',
    domain: 'education',
    description: 'Analyzes learning goals and creates personalized study schedules with recommended resources.',
    inputs: ['learning_goals', 'available_time', 'preferences'],
    outputs: ['study_plan', 'resource_list', 'milestones'],
    requiredIntegrations: ['notion', 'openai'],
    workflows: ['wf-plan-learning-notes'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Plan Completion', description: 'Goals achieved' },
      { name: 'User Satisfaction', description: 'Plan helpfulness' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 20,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'personal',
    statusNote: 'Coming Q3',
    catalogGroup: 'personal',
    family: 'learning',
    tags: ['learning', 'study', 'education', 'planning'],
    visibility: 'public',
  },
  {
    id: 'agent-paper-summarizer',
    name: 'Paper Summarizer',
    outcome: 'Summarize academic papers and research',
    domain: 'education',
    description: 'Reads academic papers and generates structured summaries with key findings and methodology.',
    inputs: ['paper_url', 'summary_format', 'focus_areas'],
    outputs: ['summary', 'key_findings', 'methodology', 'citations'],
    requiredIntegrations: ['apify', 'openai'],
    workflows: ['wf-09', 'wf-plan-learning-notes'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Summary Quality', description: 'Accuracy and completeness' },
      { name: 'Time Saved', description: 'Minutes saved per paper' },
    ],
    complexity: 'S',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 15,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'personal',
    statusNote: 'Coming Q3',
    catalogGroup: 'personal',
    family: 'learning',
    tags: ['research', 'papers', 'summarization', 'education'],
    visibility: 'public',
  },
]
