import type { AgentTemplate } from '../types'

// Sales / RevOps agents (16)
export const salesAgentTemplates: AgentTemplate[] = [
  {
    id: 'agent-lead-scoring-assistant',
    name: 'Lead Scoring Assistant',
    outcome: 'Prioritize leads with AI-powered scoring',
    domain: 'sales',
    description: 'Analyzes lead data and behavior signals to generate intelligent lead scores for prioritization.',
    inputs: ['lead_data', 'behavior_signals', 'scoring_criteria'],
    outputs: ['lead_score', 'score_breakdown', 'recommended_action'],
    requiredIntegrations: ['google-sheets'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Scoring Accuracy', description: 'Correlation with conversion' },
      { name: 'Time Saved', description: 'Hours saved on manual scoring' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: 29,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-follow-up-sequence-manager',
    name: 'Follow-up Sequence Manager',
    outcome: 'Automate sales follow-up sequences',
    domain: 'sales',
    description: 'Manages multi-touch follow-up sequences with intelligent timing and personalization.',
    inputs: ['prospect_data', 'sequence_template', 'engagement_history'],
    outputs: ['next_touchpoint', 'personalized_message', 'timing_recommendation'],
    requiredIntegrations: ['gmail'],
    workflows: [],
    riskLevel: 'high',
    hitl: 'required',
    kpis: [
      { name: 'Sequence Completion', description: 'Sequences completed' },
      { name: 'Response Rate', description: 'Prospect responses' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 30,
    monthlyPrice: 49,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Buildable on request',
  },
  {
    id: 'agent-proposal-generator',
    name: 'Proposal Generator',
    outcome: 'Create proposals in minutes, not hours',
    domain: 'sales',
    description: 'Generates customized sales proposals using templates and prospect-specific information.',
    inputs: ['prospect_info', 'requirements', 'pricing_config'],
    outputs: ['proposal_draft', 'pricing_table', 'customization_suggestions'],
    requiredIntegrations: ['google-drive', 'openai'],
    workflows: [],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Time to Proposal', description: 'Minutes to generate' },
      { name: 'Proposal Quality', description: 'Acceptance rate' },
    ],
    complexity: 'L',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 45,
    monthlyPrice: 79,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-objection-playbook-bot',
    name: 'Objection Playbook Bot',
    outcome: 'Handle objections like a pro',
    domain: 'sales',
    description: 'Provides real-time objection handling suggestions based on your playbook and past successes.',
    inputs: ['objection_text', 'deal_context', 'playbook'],
    outputs: ['suggested_responses', 'success_examples', 'resources'],
    requiredIntegrations: ['openai', 'notion'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Response Helpfulness', description: 'Rep satisfaction' },
      { name: 'Objection Overcome', description: 'Deals progressed' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Buildable on request',
  },
  {
    id: 'agent-crm-hygiene-enforcer',
    name: 'CRM Hygiene Enforcer',
    outcome: 'Keep your CRM clean and accurate',
    domain: 'sales',
    description: 'Monitors CRM data quality, identifies issues, and prompts reps to update stale records.',
    inputs: ['crm_data', 'hygiene_rules'],
    outputs: ['issues_found', 'update_prompts', 'quality_score'],
    requiredIntegrations: ['google-sheets', 'slack'],
    workflows: [],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Data Quality', description: 'CRM hygiene score' },
      { name: 'Update Rate', description: 'Prompted updates completed' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-deal-stale-detector',
    name: 'Deal Stale Detector',
    outcome: 'Never let deals go stale',
    domain: 'sales',
    description: 'Identifies deals with no recent activity and suggests re-engagement strategies.',
    inputs: ['deal_data', 'activity_history', 'stale_thresholds'],
    outputs: ['stale_deals', 'recommended_actions', 'priority_ranking'],
    requiredIntegrations: ['google-sheets', 'slack'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Stale Detection', description: 'Stale deals identified' },
      { name: 'Reactivation Rate', description: 'Stale deals revived' },
    ],
    complexity: 'S',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 15,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-call-thread-summarizer',
    name: 'Call / Thread Summarizer',
    outcome: 'Summarize calls and threads instantly',
    domain: 'sales',
    description: 'Generates concise summaries of sales calls and email threads with key points and next steps.',
    inputs: ['call_transcript', 'thread_content'],
    outputs: ['summary', 'key_points', 'action_items', 'sentiment'],
    requiredIntegrations: ['openai'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Summary Quality', description: 'Usefulness rating' },
      { name: 'Time Saved', description: 'Minutes saved per call' },
    ],
    complexity: 'S',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 10,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Buildable on request',
  },
  {
    id: 'agent-competitive-battlecard-maker',
    name: 'Competitive Battlecard Maker',
    outcome: 'Win against competitors with data',
    domain: 'sales',
    description: 'Generates and updates competitive battlecards with latest intel for sales teams.',
    inputs: ['competitor_info', 'product_comparison', 'win_loss_data'],
    outputs: ['battlecard', 'talk_tracks', 'differentiators'],
    requiredIntegrations: ['notion', 'exa', 'serpapi'],
    workflows: ['wf-05'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Battlecard Usage', description: 'Usage in competitive deals' },
      { name: 'Win Rate Impact', description: 'Competitive win rate' },
    ],
    complexity: 'M',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 30,
    monthlyPrice: null,
    availability: 'available',
    audience: 'business',
    catalogGroup: 'sales',
    family: 'research-intel',
    tags: ['competitive-intel', 'battlecards', 'sales'],
    visibility: 'variant',
    variantOf: 'agent-competitor-intel',
  },
  {
    id: 'agent-outbound-personalizer',
    name: 'Outbound Personalizer',
    outcome: 'Personalize outreach at scale',
    domain: 'sales',
    description: 'Researches prospects and generates personalized outreach messages based on their context.',
    inputs: ['prospect_list', 'template', 'research_depth'],
    outputs: ['personalized_messages', 'research_notes', 'best_timing'],
    requiredIntegrations: ['apify', 'openai'],
    workflows: [],
    riskLevel: 'high',
    hitl: 'required',
    kpis: [
      { name: 'Personalization Quality', description: 'Relevance score' },
      { name: 'Response Rate', description: 'Prospect responses' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 30,
    monthlyPrice: 49,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-warm-intro-finder',
    name: 'Warm Intro Finder',
    outcome: 'Find paths to warm introductions',
    domain: 'sales',
    description: 'Analyzes network connections to find warm introduction paths to target prospects.',
    inputs: ['target_prospect', 'network_data'],
    outputs: ['intro_paths', 'connection_strength', 'outreach_suggestions'],
    requiredIntegrations: ['google-sheets'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Paths Found', description: 'Intro paths identified' },
      { name: 'Intro Success', description: 'Successful introductions' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Buildable on request',
  },
  {
    id: 'agent-rfp-intake-bot',
    name: 'RFP Intake Bot',
    outcome: 'Process RFPs quickly and accurately',
    domain: 'sales',
    description: 'Parses RFP documents, extracts requirements, and pre-fills response templates.',
    inputs: ['rfp_document', 'response_library'],
    outputs: ['requirements_list', 'pre_filled_responses', 'gap_analysis'],
    requiredIntegrations: ['google-drive', 'openai'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'recommended',
    kpis: [
      { name: 'Processing Speed', description: 'Time to parse RFP' },
      { name: 'Response Coverage', description: 'Pre-filled sections' },
    ],
    complexity: 'L',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 45,
    monthlyPrice: 79,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Buildable on request',
  },
  {
    id: 'agent-demo-recap-sender',
    name: 'Demo Recap Sender',
    outcome: 'Follow up demos with perfect recaps',
    domain: 'sales',
    description: 'Automatically generates and sends personalized demo recap emails with key points.',
    inputs: ['demo_notes', 'attendees', 'next_steps'],
    outputs: ['recap_email', 'resource_links', 'calendar_invite'],
    requiredIntegrations: ['gmail', 'google-calendar'],
    workflows: [],
    riskLevel: 'high',
    hitl: 'required',
    kpis: [
      { name: 'Recap Speed', description: 'Time to send recap' },
      { name: 'Engagement', description: 'Recap open rate' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 20,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-pipeline-weekly-digest',
    name: 'Pipeline Weekly Digest',
    outcome: 'Weekly pipeline health report',
    domain: 'sales',
    description: 'Generates weekly pipeline health reports with movement analysis and forecasting.',
    inputs: ['pipeline_data', 'historical_data'],
    outputs: ['digest', 'movement_analysis', 'forecast', 'at_risk_deals'],
    requiredIntegrations: ['google-sheets', 'slack'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Report Accuracy', description: 'Forecast accuracy' },
      { name: 'Stakeholder Engagement', description: 'Report actions taken' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-multithreading-planner',
    name: 'Multi-threading Planner',
    outcome: 'Build multi-threaded relationships',
    domain: 'sales',
    description: 'Identifies stakeholders and suggests multi-threading strategies for complex deals.',
    inputs: ['deal_data', 'org_chart', 'engagement_history'],
    outputs: ['stakeholder_map', 'threading_strategy', 'outreach_plan'],
    requiredIntegrations: ['google-sheets'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Stakeholders Engaged', description: 'Contacts per deal' },
      { name: 'Deal Velocity', description: 'Multi-threaded deal speed' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Buildable on request',
  },
  {
    id: 'agent-sales-ops-concierge',
    name: 'Sales Ops Concierge',
    outcome: 'On-demand sales ops assistance',
    domain: 'sales',
    description: 'Virtual assistant for sales ops queries, data lookups, and process guidance.',
    inputs: ['query', 'context'],
    outputs: ['answer', 'data', 'process_steps', 'resources'],
    requiredIntegrations: ['slack', 'openai'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Query Resolution', description: 'Queries answered successfully' },
      { name: 'Time Saved', description: 'Minutes saved per query' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 20,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-lead-gen-attachment-evaluator',
    name: 'Lead Gen Attachment Evaluator',
    outcome: 'Screen lead submissions automatically',
    domain: 'sales',
    description: 'Evaluates attachments from lead generation forms (resumes, RFIs, etc.) against criteria.',
    inputs: ['attachment', 'evaluation_criteria', 'lead_source'],
    outputs: ['score', 'qualification', 'key_highlights', 'next_steps'],
    requiredIntegrations: ['gmail', 'google-sheets'],
    workflows: ['wf-25'],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Evaluation Speed', description: 'Time per attachment' },
      { name: 'Qualification Accuracy', description: 'Correct assessments' },
    ],
    complexity: 'M',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'available',
    audience: 'business',
    catalogGroup: 'sales',
    family: 'documents-attachments',
    tags: ['lead-gen', 'evaluation', 'attachments'],
    visibility: 'variant',
    variantOf: 'agent-resume-evaluator',
  },
]
