import type { WorkflowTemplate } from '../types'

// New workflows to add to the catalog (wf-06 through wf-30, excluding already existing wf-09, wf-10, wf-24, wf-25, wf-26)
export const newWorkflowTemplates: WorkflowTemplate[] = [
  {
    id: 'wf-06',
    name: 'Recipe Recommendations with Qdrant & Mistral',
    summary: 'Search and recommend recipes using vector similarity and Mistral AI',
    trigger: 'manual',
    integrations: ['qdrant', 'mistral'],
    output: 'Personalized recipe recommendations based on preferences and ingredients',
    useCase: 'Build intelligent recipe discovery with semantic search capabilities',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Manual Trigger', description: 'User initiates search' },
      { id: 'n2', type: 'ai', name: 'Qdrant Search', description: 'Vector similarity search' },
      { id: 'n3', type: 'ai', name: 'Mistral Format', description: 'Format recommendations' },
    ],
    availability: 'available',
    source: 'awesome-n8n-templates',
  },
  {
    id: 'wf-07',
    name: 'Reconcile Rent Payments with Local Excel & OpenAI',
    summary: 'Match rent payments against expected amounts using AI-assisted reconciliation',
    trigger: 'manual',
    integrations: ['excel', 'openai'],
    output: 'Reconciliation report with matched and unmatched payments',
    useCase: 'Automate tedious financial reconciliation tasks',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Manual Trigger', description: 'Start reconciliation' },
      { id: 'n2', type: 'extract', name: 'Read Excel', description: 'Load payment data' },
      { id: 'n3', type: 'ai', name: 'AI Reconcile', description: 'Match payments' },
      { id: 'n4', type: 'action', name: 'Generate Report', description: 'Output results' },
    ],
    availability: 'available',
    source: 'awesome-n8n-templates',
  },
  {
    id: 'wf-08',
    name: 'Scrape News Site Without RSS to NocoDB',
    summary: 'Extract news from sites lacking RSS feeds and store in NocoDB',
    trigger: 'cron',
    integrations: ['apify', 'openai', 'nocodb'],
    output: 'Structured news entries in NocoDB database',
    useCase: 'Monitor news sources that do not provide RSS feeds',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Schedule', description: 'Run every 6 hours' },
      { id: 'n2', type: 'fetch', name: 'Apify Scrape', description: 'Extract articles' },
      { id: 'n3', type: 'ai', name: 'AI Parse', description: 'Structure content' },
      { id: 'n4', type: 'action', name: 'NocoDB Insert', description: 'Store articles' },
    ],
    availability: 'available',
    source: 'awesome-n8n-templates',
  },
  {
    id: 'wf-11',
    name: 'Google Analytics to AI to Baserow',
    summary: 'Fetch GA data, analyze trends with AI, and log insights to Baserow',
    trigger: 'cron',
    integrations: ['google-analytics', 'openai', 'baserow'],
    output: 'AI-analyzed traffic insights in Baserow',
    useCase: 'Automated analytics reporting with AI interpretation',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Daily Schedule', description: 'Run at 7am' },
      { id: 'n2', type: 'fetch', name: 'GA Fetch', description: 'Get analytics data' },
      { id: 'n3', type: 'ai', name: 'AI Analyze', description: 'Generate insights' },
      { id: 'n4', type: 'action', name: 'Baserow Update', description: 'Log insights' },
    ],
    availability: 'available',
    source: 'awesome-n8n-templates',
  },
  {
    id: 'wf-12',
    name: 'Workplace Pattern Detection with AI',
    summary: 'Analyze workplace data to detect behavioral patterns and anomalies',
    trigger: 'manual',
    integrations: ['openai'],
    output: 'Pattern analysis report with actionable insights',
    useCase: 'Identify workplace trends and potential issues proactively',
    riskLevel: 'medium',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Manual Trigger', description: 'Start analysis' },
      { id: 'n2', type: 'extract', name: 'Load Data', description: 'Import workplace data' },
      { id: 'n3', type: 'ai', name: 'Pattern Analysis', description: 'Detect patterns' },
      { id: 'n4', type: 'action', name: 'Report', description: 'Generate findings' },
    ],
    availability: 'available',
    source: 'awesome-n8n-templates',
  },
  {
    id: 'wf-13',
    name: 'SERPBear to AI to Baserow',
    summary: 'Track keyword rankings with SERPBear and log AI analysis to Baserow',
    trigger: 'cron',
    integrations: ['serpbear', 'openrouter', 'baserow'],
    output: 'SEO ranking insights and recommendations in Baserow',
    useCase: 'Automated SEO monitoring with AI-powered recommendations',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Weekly Schedule', description: 'Run Mondays' },
      { id: 'n2', type: 'fetch', name: 'SERPBear Fetch', description: 'Get rankings' },
      { id: 'n3', type: 'ai', name: 'OpenRouter Analyze', description: 'Analyze trends' },
      { id: 'n4', type: 'action', name: 'Baserow Log', description: 'Store insights' },
    ],
    availability: 'available',
    source: 'awesome-n8n-templates',
  },
  {
    id: 'wf-14',
    name: 'Umami to AI to Baserow',
    summary: 'Extract Umami analytics and generate AI-powered insights in Baserow',
    trigger: 'cron',
    integrations: ['umami', 'openrouter', 'baserow'],
    output: 'Privacy-focused analytics insights in Baserow',
    useCase: 'Self-hosted analytics with AI interpretation',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Daily Schedule', description: 'Run at 8am' },
      { id: 'n2', type: 'fetch', name: 'Umami Fetch', description: 'Get analytics' },
      { id: 'n3', type: 'ai', name: 'OpenRouter Analyze', description: 'Generate insights' },
      { id: 'n4', type: 'action', name: 'Baserow Update', description: 'Log results' },
    ],
    availability: 'available',
    source: 'awesome-n8n-templates',
  },
  {
    id: 'wf-15',
    name: 'Survey Insights with Qdrant / Python / Extractor',
    summary: 'Process survey responses with vector embeddings and Python analysis',
    trigger: 'manual',
    integrations: ['qdrant', 'python'],
    output: 'Deep survey insights with theme clustering',
    useCase: 'Extract actionable insights from qualitative survey data',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Manual Trigger', description: 'Start analysis' },
      { id: 'n2', type: 'extract', name: 'Load Responses', description: 'Import survey data' },
      { id: 'n3', type: 'ai', name: 'Qdrant Embed', description: 'Create embeddings' },
      { id: 'n4', type: 'logic', name: 'Python Analysis', description: 'Cluster themes' },
    ],
    availability: 'available',
    source: 'awesome-n8n-templates',
  },
  {
    id: 'wf-16',
    name: 'Ultimate Scraper Workflow',
    summary: 'Versatile web scraping with AI-powered content extraction',
    trigger: 'webhook',
    integrations: ['apify', 'openai'],
    output: 'Structured data from any webpage',
    useCase: 'On-demand web scraping for research and data collection',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Webhook', description: 'Receive URL' },
      { id: 'n2', type: 'fetch', name: 'Apify Scrape', description: 'Extract page' },
      { id: 'n3', type: 'ai', name: 'AI Extract', description: 'Structure data' },
    ],
    availability: 'available',
    source: 'awesome-n8n-templates',
  },
  {
    id: 'wf-17',
    name: 'Vector DB Big Data Analysis Part 1',
    summary: 'Ingest and embed large datasets into Qdrant for analysis',
    trigger: 'manual',
    integrations: ['qdrant'],
    output: 'Indexed vector database ready for queries',
    useCase: 'Prepare large datasets for semantic search and analysis',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Manual Trigger', description: 'Start ingestion' },
      { id: 'n2', type: 'extract', name: 'Load Data', description: 'Import dataset' },
      { id: 'n3', type: 'ai', name: 'Generate Embeddings', description: 'Create vectors' },
      { id: 'n4', type: 'action', name: 'Qdrant Upsert', description: 'Store vectors' },
    ],
    availability: 'available',
    source: 'awesome-n8n-templates',
  },
  {
    id: 'wf-18',
    name: 'Vector DB Big Data Analysis Part 2',
    summary: 'Query and analyze embedded data with semantic search',
    trigger: 'manual',
    integrations: ['qdrant'],
    output: 'Analysis results from vector similarity queries',
    useCase: 'Run semantic queries on large embedded datasets',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Manual Trigger', description: 'Start query' },
      { id: 'n2', type: 'ai', name: 'Qdrant Query', description: 'Semantic search' },
      { id: 'n3', type: 'logic', name: 'Process Results', description: 'Format output' },
    ],
    availability: 'available',
    source: 'awesome-n8n-templates',
  },
  {
    id: 'wf-19',
    name: 'Vector DB Anomaly Detection Part 2',
    summary: 'Detect anomalies in vector-embedded data',
    trigger: 'manual',
    integrations: ['qdrant'],
    output: 'Anomaly detection report with outliers identified',
    useCase: 'Find unusual patterns in embedded datasets',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Manual Trigger', description: 'Start detection' },
      { id: 'n2', type: 'ai', name: 'Qdrant Search', description: 'Find outliers' },
      { id: 'n3', type: 'logic', name: 'Anomaly Score', description: 'Calculate scores' },
    ],
    availability: 'available',
    source: 'awesome-n8n-templates',
  },
  {
    id: 'wf-20',
    name: 'Vector DB Anomaly Detection Part 3',
    summary: 'Advanced anomaly clustering and alerting',
    trigger: 'manual',
    integrations: ['qdrant'],
    output: 'Clustered anomalies with severity classifications',
    useCase: 'Group and prioritize detected anomalies',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Manual Trigger', description: 'Start clustering' },
      { id: 'n2', type: 'ai', name: 'Qdrant Cluster', description: 'Group anomalies' },
      { id: 'n3', type: 'logic', name: 'Severity Score', description: 'Classify severity' },
    ],
    availability: 'available',
    source: 'awesome-n8n-templates',
  },
  {
    id: 'wf-21',
    name: 'Visual Regression Testing with Apify + AI Vision',
    summary: 'Capture screenshots and detect visual changes with AI',
    trigger: 'cron',
    integrations: ['apify', 'openai'],
    output: 'Visual regression report with detected changes',
    useCase: 'Automated QA for UI consistency',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Schedule', description: 'Run nightly' },
      { id: 'n2', type: 'fetch', name: 'Apify Screenshot', description: 'Capture pages' },
      { id: 'n3', type: 'ai', name: 'Vision Compare', description: 'Detect changes' },
      { id: 'n4', type: 'action', name: 'Report', description: 'Generate diff report' },
    ],
    availability: 'available',
    source: 'awesome-n8n-templates',
  },
  {
    id: 'wf-22',
    name: 'Perplexity Research to HTML',
    summary: 'Research any topic with Perplexity AI and output formatted HTML',
    trigger: 'manual',
    integrations: ['perplexity'],
    output: 'Research report in clean HTML format',
    useCase: 'Rapid research with publication-ready output',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Manual Trigger', description: 'Start research' },
      { id: 'n2', type: 'ai', name: 'Perplexity Query', description: 'Research topic' },
      { id: 'n3', type: 'logic', name: 'Format HTML', description: 'Generate output' },
    ],
    availability: 'available',
    source: 'awesome-n8n-templates',
  },
  {
    id: 'wf-23',
    name: 'Gmail to Google Drive Import',
    summary: 'Automatically import Gmail attachments to organized Drive folders',
    trigger: 'email',
    integrations: ['gmail', 'google-drive'],
    output: 'Attachments organized in Google Drive',
    useCase: 'Automated email attachment archival',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Gmail Trigger', description: 'New email' },
      { id: 'n2', type: 'extract', name: 'Get Attachments', description: 'Extract files' },
      { id: 'n3', type: 'action', name: 'Drive Upload', description: 'Save to folder' },
    ],
    availability: 'available',
    source: 'zie619',
    visibility: 'utility',
    catalogGroups: ['support', 'personal'],
    tags: ['email', 'attachments', 'drive'],
  },
  {
    id: 'wf-27',
    name: 'Gmail Move Binary Data Send',
    summary: 'Process and forward email attachments as binary data',
    trigger: 'email',
    integrations: ['gmail'],
    output: 'Forwarded attachments with binary handling',
    useCase: 'Automated attachment routing and processing',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Gmail Trigger', description: 'New email' },
      { id: 'n2', type: 'extract', name: 'Extract Binary', description: 'Get attachment' },
      { id: 'n3', type: 'action', name: 'Forward', description: 'Send binary data' },
    ],
    availability: 'available',
    source: 'zie619',
    visibility: 'hidden',
  },
  {
    id: 'wf-28',
    name: 'Gmail Sticky Note Create Triggered',
    summary: 'Create sticky notes from starred or labeled emails',
    trigger: 'email',
    integrations: ['gmail'],
    output: 'Sticky notes created from email content',
    useCase: 'Turn important emails into visual reminders',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Gmail Trigger', description: 'Starred email' },
      { id: 'n2', type: 'extract', name: 'Parse Content', description: 'Extract key info' },
      { id: 'n3', type: 'action', name: 'Create Note', description: 'Generate sticky' },
    ],
    availability: 'available',
    source: 'zie619',
    visibility: 'hidden',
  },
  {
    id: 'wf-29',
    name: 'Gmail Sticky Note Create Triggered Variant',
    summary: 'Alternative sticky note creation with custom formatting',
    trigger: 'email',
    integrations: ['gmail'],
    output: 'Custom-formatted sticky notes from emails',
    useCase: 'Personalized email-to-note conversion',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Gmail Trigger', description: 'Label trigger' },
      { id: 'n2', type: 'logic', name: 'Custom Format', description: 'Apply template' },
      { id: 'n3', type: 'action', name: 'Create Note', description: 'Generate sticky' },
    ],
    availability: 'available',
    source: 'zie619',
    visibility: 'hidden',
  },
  {
    id: 'wf-30',
    name: 'Gmail Sticky Note Send Triggered',
    summary: 'Send sticky note contents back via email',
    trigger: 'email',
    integrations: ['gmail'],
    output: 'Email sent with sticky note content',
    useCase: 'Share note reminders via email',
    riskLevel: 'low',
    version: '1.0.0',
    changelog: ['1.0.0: Initial release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Gmail Trigger', description: 'Request email' },
      { id: 'n2', type: 'logic', name: 'Fetch Notes', description: 'Get note content' },
      { id: 'n3', type: 'action', name: 'Gmail Send', description: 'Email notes' },
    ],
    availability: 'available',
    source: 'zie619',
    visibility: 'hidden',
  },
]
