import type { AgentTemplate } from '../../control-plane/types';

// Research / Content / Marketing agents (16)
export const researchAgentTemplates: AgentTemplate[] = [
  {
    id: 'agent-no-rss-news-scraper',
    name: 'No-RSS News Scraper',
    outcome: 'Monitor news sites without RSS feeds',
    domain: 'research',
    description:
      'Scrapes news from websites that do not provide RSS feeds and stores articles in a structured database.',
    inputs: ['target_sites', 'keywords', 'frequency'],
    outputs: ['articles', 'summaries', 'stored_records'],
    requiredIntegrations: ['apify', 'openai', 'nocodb'],
    workflows: ['wf-08'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Articles Captured', description: 'News items collected' },
      { name: 'Relevance Score', description: 'Content relevance' },
    ],
    complexity: 'M',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'available',
    audience: 'both',
  },
  {
    id: 'agent-seo-pulse-reporter',
    name: 'SEO Pulse Reporter',
    outcome: 'Weekly SEO health and ranking report',
    domain: 'marketing',
    description:
      'Monitors keyword rankings and SEO metrics, delivering AI-analyzed insights weekly.',
    inputs: ['keywords', 'competitors', 'site_url'],
    outputs: ['ranking_report', 'trend_analysis', 'recommendations'],
    requiredIntegrations: ['serpbear', 'openrouter', 'baserow'],
    workflows: ['wf-13'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Ranking Accuracy', description: 'Data accuracy' },
      { name: 'Actionable Insights', description: 'Recommendations acted on' },
    ],
    complexity: 'M',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'available',
    audience: 'business',
  },
  {
    id: 'agent-ga-insight-bot',
    name: 'GA Insight Bot',
    outcome: 'AI-powered Google Analytics insights',
    domain: 'marketing',
    description:
      'Fetches Google Analytics data and generates AI-powered insights and recommendations.',
    inputs: ['ga_property', 'date_range', 'focus_areas'],
    outputs: ['insights', 'anomalies', 'recommendations'],
    requiredIntegrations: ['google-analytics', 'openai', 'baserow'],
    workflows: ['wf-11'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Insight Quality', description: 'Actionable insights rate' },
      { name: 'Time Saved', description: 'Hours saved on analysis' },
    ],
    complexity: 'M',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'available',
    audience: 'business',
  },
  {
    id: 'agent-research-to-html-publisher',
    name: 'Perplexity Research to HTML Publisher',
    outcome: 'Research any topic and publish HTML',
    domain: 'marketing',
    description:
      'Uses Perplexity AI to research topics and outputs publication-ready HTML content.',
    inputs: ['research_topic', 'output_format', 'depth'],
    outputs: ['html_content', 'sources', 'summary'],
    requiredIntegrations: ['perplexity'],
    workflows: ['wf-22'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Research Quality', description: 'Content accuracy' },
      { name: 'Time to Publish', description: 'Minutes to ready content' },
    ],
    complexity: 'S',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 15,
    monthlyPrice: null,
    availability: 'available',
    audience: 'both',
  },
  {
    id: 'agent-survey-insights-analyst',
    name: 'Survey Insights Analyst',
    outcome: 'Deep insights from survey responses',
    domain: 'research',
    description:
      'Processes survey data with vector embeddings to extract themes and actionable insights.',
    inputs: ['survey_responses', 'questions', 'analysis_focus'],
    outputs: ['themes', 'sentiment', 'recommendations', 'visualizations'],
    requiredIntegrations: ['qdrant', 'python'],
    workflows: ['wf-15'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Insight Depth', description: 'Theme discovery quality' },
      { name: 'Processing Speed', description: 'Responses per minute' },
    ],
    complexity: 'L',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 35,
    monthlyPrice: null,
    availability: 'available',
    audience: 'business',
  },
  {
    id: 'agent-recipe-recommender',
    name: 'Recipe Recommender Demo',
    outcome: 'Semantic recipe search and recommendations',
    domain: 'research',
    description:
      'Demo agent showcasing vector search for recipe recommendations based on preferences.',
    inputs: ['preferences', 'ingredients', 'dietary_restrictions'],
    outputs: ['recipes', 'similarity_scores', 'substitutions'],
    requiredIntegrations: ['qdrant', 'mistral'],
    workflows: ['wf-06'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Recommendation Relevance', description: 'User satisfaction' },
      { name: 'Search Speed', description: 'Query response time' },
    ],
    complexity: 'M',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'available',
    audience: 'personal',
    catalogGroup: 'personal',
    family: 'demos-labs',
    tags: ['demo', 'recipes', 'vector-search'],
    visibility: 'hidden',
  },
  {
    id: 'agent-scraper-swiss-army-knife',
    name: 'Scraper Swiss Army Knife',
    outcome: 'Versatile web scraping on demand',
    domain: 'research',
    description:
      'Flexible web scraping agent that extracts structured data from any webpage via API.',
    inputs: ['url', 'extraction_schema', 'options'],
    outputs: ['extracted_data', 'raw_content', 'metadata'],
    requiredIntegrations: ['apify', 'openai'],
    workflows: ['wf-16'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Extraction Accuracy', description: 'Data quality' },
      { name: 'Coverage', description: 'Sites successfully scraped' },
    ],
    complexity: 'M',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 20,
    monthlyPrice: null,
    availability: 'available',
    audience: 'both',
  },
  {
    id: 'agent-visual-regression-qa',
    name: 'Visual Regression QA',
    outcome: 'Automated visual testing for websites',
    domain: 'research',
    description: 'Captures screenshots and uses AI vision to detect unintended visual changes.',
    inputs: ['urls', 'baseline_images', 'tolerance'],
    outputs: ['diff_report', 'changed_areas', 'severity'],
    requiredIntegrations: ['apify', 'openai'],
    workflows: ['wf-21'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Detection Accuracy', description: 'Issues correctly identified' },
      { name: 'False Positive Rate', description: 'Incorrect alerts' },
    ],
    complexity: 'M',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 30,
    monthlyPrice: null,
    availability: 'available',
    audience: 'business',
  },
  {
    id: 'agent-workplace-pattern-detector',
    name: 'Workplace Pattern Detector',
    outcome: 'Identify patterns in workplace data',
    domain: 'ops',
    description:
      'Analyzes workplace data to detect behavioral patterns, trends, and potential issues.',
    inputs: ['workplace_data', 'analysis_type'],
    outputs: ['patterns', 'anomalies', 'recommendations'],
    requiredIntegrations: ['openai'],
    workflows: ['wf-12'],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Pattern Accuracy', description: 'Valid patterns detected' },
      { name: 'Actionable Rate', description: 'Patterns acted upon' },
    ],
    complexity: 'M',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'available',
    audience: 'business',
  },
  {
    id: 'agent-rent-reconciliation-bot',
    name: 'Rent Reconciliation Bot',
    outcome: 'Automate rent payment reconciliation',
    domain: 'finance',
    description: 'Matches rent payments against expected amounts using AI-assisted reconciliation.',
    inputs: ['payment_data', 'expected_amounts', 'tolerance'],
    outputs: ['reconciliation_report', 'matched', 'unmatched', 'discrepancies'],
    requiredIntegrations: ['excel', 'openai'],
    workflows: ['wf-07'],
    riskLevel: 'low',
    hitl: 'recommended',
    kpis: [
      { name: 'Match Accuracy', description: 'Correct matches' },
      { name: 'Time Saved', description: 'Hours saved monthly' },
    ],
    complexity: 'M',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'available',
    audience: 'business',
  },
  {
    id: 'agent-vector-analytics-lab',
    name: 'Vector Analytics Lab',
    outcome: 'Advanced analytics with vector databases',
    domain: 'research',
    description:
      'Multi-part analytics suite for big data analysis and anomaly detection using vector embeddings.',
    inputs: ['dataset', 'analysis_type', 'parameters'],
    outputs: ['analysis_results', 'visualizations', 'anomalies'],
    requiredIntegrations: ['qdrant'],
    workflows: ['wf-17', 'wf-18', 'wf-19', 'wf-20'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Analysis Depth', description: 'Insight quality' },
      { name: 'Processing Scale', description: 'Data volume handled' },
    ],
    complexity: 'L',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 45,
    monthlyPrice: 49,
    availability: 'available',
    audience: 'business',
    catalogGroup: 'research',
    family: 'demos-labs',
    tags: ['demo', 'vector', 'analytics', 'big-data'],
    visibility: 'hidden',
  },
  {
    id: 'agent-review-theme-miner',
    name: 'Review Theme Miner',
    outcome: 'Extract themes from customer reviews',
    domain: 'marketing',
    description:
      'Analyzes customer reviews to extract recurring themes, sentiment patterns, and improvement areas.',
    inputs: ['reviews', 'time_period', 'focus_areas'],
    outputs: ['themes', 'sentiment_breakdown', 'priority_issues'],
    requiredIntegrations: ['trustpilot', 'openai'],
    workflows: ['wf-10'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Theme Accuracy', description: 'Correct theme identification' },
      { name: 'Coverage', description: 'Reviews analyzed' },
    ],
    complexity: 'M',
    version: '0.9.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-content-calendar-builder',
    name: 'Content Calendar Builder',
    outcome: 'Plan content with AI assistance',
    domain: 'marketing',
    description:
      'Generates content calendar suggestions based on trends, events, and audience insights.',
    inputs: ['topics', 'channels', 'frequency', 'events'],
    outputs: ['calendar', 'content_ideas', 'optimal_timing'],
    requiredIntegrations: ['notion', 'openai'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'recommended',
    kpis: [
      { name: 'Calendar Adoption', description: 'Suggestions used' },
      { name: 'Content Performance', description: 'Engagement improvement' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'both',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-repurposing-machine',
    name: 'Repurposing Machine',
    outcome: 'Transform content across formats',
    domain: 'marketing',
    description:
      'Repurposes long-form content into multiple formats (social posts, summaries, threads).',
    inputs: ['source_content', 'target_formats', 'tone'],
    outputs: ['repurposed_content', 'format_variants', 'scheduling_suggestions'],
    requiredIntegrations: ['openai'],
    workflows: [],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Variants Created', description: 'Content pieces generated' },
      { name: 'Quality Score', description: 'Content quality rating' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 20,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'both',
    statusNote: 'Buildable on request',
  },
  {
    id: 'agent-brand-mention-radar',
    name: 'Brand Mention Radar',
    outcome: 'Track brand mentions across the web',
    domain: 'marketing',
    description: 'Monitors web and social for brand mentions, alerting on significant discussions.',
    inputs: ['brand_keywords', 'sources', 'sentiment_filter'],
    outputs: ['mentions', 'sentiment', 'alerts', 'report'],
    requiredIntegrations: ['apify', 'openai'],
    workflows: ['wf-03', 'wf-08'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Mention Coverage', description: 'Mentions captured' },
      { name: 'Alert Relevance', description: 'Actionable alerts' },
    ],
    complexity: 'M',
    version: '0.9.0',
    channel: 'beta',
    setupTimeMinutes: 30,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'both',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-community-reply-drafter',
    name: 'Community Reply Drafter',
    outcome: 'Draft community responses at scale',
    domain: 'marketing',
    description:
      'Drafts responses to community posts, comments, and discussions in your brand voice.',
    inputs: ['post_content', 'brand_voice', 'response_type'],
    outputs: ['draft_reply', 'tone_check', 'suggested_resources'],
    requiredIntegrations: ['openai'],
    workflows: [],
    riskLevel: 'high',
    hitl: 'required',
    kpis: [
      { name: 'Draft Acceptance', description: 'Drafts used as-is' },
      { name: 'Response Time', description: 'Time to draft' },
    ],
    complexity: 'S',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 15,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'both',
    statusNote: 'Buildable on request',
  },
];
