import type { AgentTemplate } from '../../control-plane/types';

// Support / Customer Ops agents (20)
export const supportAgentTemplates: AgentTemplate[] = [
  {
    id: 'agent-slack-ticket-factory',
    name: 'Slack Ticket Factory',
    outcome: 'Turn Slack messages into trackable tickets',
    domain: 'support',
    description:
      'Converts Slack messages (via emoji reactions or commands) into properly formatted support tickets with context preservation.',
    inputs: ['slack_message', 'channel', 'user'],
    outputs: ['ticket_id', 'ticket_url', 'confirmation'],
    requiredIntegrations: ['slack', 'linear'],
    workflows: ['wf-02'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Ticket Creation Rate', description: 'Messages converted to tickets' },
      { name: 'Context Quality', description: 'Completeness of ticket info' },
    ],
    complexity: 'S',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 15,
    monthlyPrice: null,
    availability: 'available',
    audience: 'business',
    catalogGroup: 'support',
    family: 'ticketing',
    tags: ['slack', 'ticketing', 'linear'],
    visibility: 'variant',
    variantOf: 'agent-ticket-router',
  },
  {
    id: 'agent-sla-sentinel',
    name: 'SLA Sentinel',
    outcome: 'Never miss an SLA deadline',
    domain: 'support',
    description:
      'Monitors ticket SLAs, sends alerts before breaches, and escalates overdue items automatically.',
    inputs: ['ticket_data', 'sla_rules'],
    outputs: ['alerts', 'escalations', 'sla_report'],
    requiredIntegrations: ['linear', 'slack'],
    workflows: [],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'SLA Compliance', description: 'Tickets meeting SLA' },
      { name: 'Breach Prevention', description: 'Alerts before breaches' },
    ],
    complexity: 'M',
    version: '0.9.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: 29,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
    catalogGroup: 'support',
    family: 'ticketing',
    tags: ['sla', 'escalation', 'ticketing'],
    visibility: 'public',
  },
  {
    id: 'agent-bug-report-normalizer',
    name: 'Bug Report Normalizer',
    outcome: 'Standardize bug reports automatically',
    domain: 'support',
    description:
      'Takes unstructured bug reports and normalizes them into a standard format with reproduction steps and severity.',
    inputs: ['bug_report', 'product_context'],
    outputs: ['normalized_report', 'severity', 'affected_area'],
    requiredIntegrations: ['linear', 'openai'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Report Quality', description: 'Completeness score' },
      { name: 'Processing Speed', description: 'Time to normalize' },
    ],
    complexity: 'S',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 15,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Buildable on request',
    catalogGroup: 'support',
    family: 'ticketing',
    tags: ['bugs', 'normalization', 'ticketing'],
    visibility: 'public',
  },
  {
    id: 'agent-refund-triage-assistant',
    name: 'Refund Triage Assistant',
    outcome: 'Streamline refund request handling',
    domain: 'support',
    description:
      'Evaluates refund requests against policy, gathers necessary information, and routes to approval.',
    inputs: ['refund_request', 'customer_data', 'policy_rules'],
    outputs: ['recommendation', 'required_info', 'approval_queue'],
    requiredIntegrations: ['gmail', 'google-sheets'],
    workflows: [],
    riskLevel: 'high',
    hitl: 'required',
    kpis: [
      { name: 'Processing Time', description: 'Time to decision' },
      { name: 'Policy Compliance', description: 'Decisions matching policy' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 30,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Buildable on request',
  },
  {
    id: 'agent-kb-answer-drafter',
    name: 'KB Answer Drafter',
    outcome: 'Draft KB-backed responses instantly',
    domain: 'support',
    description:
      'Searches knowledge base and drafts responses to customer questions with source citations.',
    inputs: ['customer_question', 'kb_context'],
    outputs: ['draft_response', 'sources', 'confidence'],
    requiredIntegrations: ['notion', 'openai'],
    workflows: [],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Draft Accuracy', description: 'Responses used without edits' },
      { name: 'Time Saved', description: 'Minutes saved per response' },
    ],
    complexity: 'M',
    version: '0.9.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-duplicate-issue-linker',
    name: 'Duplicate Issue Linker',
    outcome: 'Automatically link duplicate issues',
    domain: 'support',
    description:
      'Detects duplicate support tickets and automatically links them to existing issues.',
    inputs: ['new_ticket', 'existing_tickets'],
    outputs: ['is_duplicate', 'linked_ticket', 'similarity_score'],
    requiredIntegrations: ['linear'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Detection Rate', description: 'Duplicates caught' },
      { name: 'False Positive Rate', description: 'Incorrect links' },
    ],
    complexity: 'S',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 15,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-escalation-router',
    name: 'Escalation Router',
    outcome: 'Smart escalation to the right expert',
    domain: 'support',
    description:
      'Routes escalated issues to the most appropriate expert based on topic, urgency, and team availability.',
    inputs: ['escalation_request', 'team_roster', 'expertise_map'],
    outputs: ['assigned_expert', 'context_summary', 'handoff_notes'],
    requiredIntegrations: ['slack', 'linear'],
    workflows: [],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Routing Accuracy', description: 'Correct expert assignment' },
      { name: 'Resolution Time', description: 'Time to resolve escalation' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Buildable on request',
  },
  {
    id: 'agent-detractor-rescue',
    name: 'CSAT / NPS Detractor Rescue',
    outcome: 'Turn detractors into promoters',
    domain: 'support',
    description: 'Identifies low CSAT/NPS scores and triggers personalized recovery workflows.',
    inputs: ['survey_response', 'customer_history'],
    outputs: ['rescue_action', 'follow_up_draft', 'escalation_flag'],
    requiredIntegrations: ['gmail', 'slack'],
    workflows: [],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Recovery Rate', description: 'Detractors converted' },
      { name: 'Response Time', description: 'Time to reach out' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 30,
    monthlyPrice: 29,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-weekly-support-digest',
    name: 'Weekly Support Digest',
    outcome: 'Comprehensive weekly support summary',
    domain: 'support',
    description:
      'Compiles weekly support metrics, trends, and highlights into an executive summary.',
    inputs: ['ticket_data', 'metrics', 'date_range'],
    outputs: ['digest', 'key_metrics', 'trends', 'recommendations'],
    requiredIntegrations: ['slack', 'google-sheets'],
    workflows: ['wf-03'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Report Completeness', description: 'Metrics coverage' },
      { name: 'Stakeholder Engagement', description: 'Report views/actions' },
    ],
    complexity: 'M',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 20,
    monthlyPrice: null,
    availability: 'available',
    audience: 'business',
  },
  {
    id: 'agent-voice-of-customer-miner',
    name: 'Voice of Customer Miner',
    outcome: 'Extract insights from customer feedback',
    domain: 'support',
    description:
      'Analyzes support tickets, reviews, and feedback to surface recurring themes and customer pain points.',
    inputs: ['feedback_data', 'time_period'],
    outputs: ['themes', 'sentiment_trends', 'priority_issues'],
    requiredIntegrations: ['google-sheets', 'openai'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Insight Accuracy', description: 'Actionable insights rate' },
      { name: 'Coverage', description: 'Feedback analyzed' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 30,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-attachment-collector',
    name: 'Attachment Collector',
    outcome: 'Gather and organize ticket attachments',
    domain: 'support',
    description:
      'Collects attachments from support tickets and organizes them for easy access and analysis.',
    inputs: ['ticket_id', 'attachment_types'],
    outputs: ['collected_files', 'organized_folder', 'metadata'],
    requiredIntegrations: ['linear', 'google-drive'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Collection Rate', description: 'Attachments captured' },
      { name: 'Organization', description: 'Files findable quickly' },
    ],
    complexity: 'S',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 15,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Buildable on request',
  },
  {
    id: 'agent-ticket-summary-crm',
    name: 'Ticket Summary to CRM',
    outcome: 'Sync ticket summaries to CRM records',
    domain: 'support',
    description: 'Summarizes support tickets and syncs key information to customer CRM records.',
    inputs: ['ticket_data', 'customer_id'],
    outputs: ['summary', 'crm_update', 'relationship_notes'],
    requiredIntegrations: ['linear', 'google-sheets'],
    workflows: [],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Sync Rate', description: 'Tickets synced to CRM' },
      { name: 'Summary Quality', description: 'Usefulness rating' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-outage-comms-coordinator',
    name: 'Outage Comms Coordinator',
    outcome: 'Coordinate outage communications',
    domain: 'support',
    description:
      'Manages customer communications during outages with templated updates and status page integration.',
    inputs: ['outage_details', 'affected_customers', 'status'],
    outputs: ['communication_sent', 'status_update', 'escalation_log'],
    requiredIntegrations: ['slack', 'gmail'],
    workflows: [],
    riskLevel: 'high',
    hitl: 'required',
    kpis: [
      { name: 'Communication Speed', description: 'Time to first update' },
      { name: 'Customer Reach', description: 'Affected customers notified' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 30,
    monthlyPrice: 49,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Buildable on request',
  },
  {
    id: 'agent-macro-suggestion-bot',
    name: 'Macro Suggestion Bot',
    outcome: 'Suggest optimal response macros',
    domain: 'support',
    description:
      'Analyzes incoming tickets and suggests the most relevant response macros to agents.',
    inputs: ['ticket_content', 'macro_library'],
    outputs: ['suggested_macros', 'confidence_scores', 'personalization_hints'],
    requiredIntegrations: ['openai'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Suggestion Accuracy', description: 'Macros used as suggested' },
      { name: 'Time Saved', description: 'Response time reduction' },
    ],
    complexity: 'S',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 15,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-churn-risk-warning',
    name: 'Churn Risk Early Warning',
    outcome: 'Identify at-risk customers early',
    domain: 'support',
    description:
      'Analyzes support patterns and behavior signals to identify customers at risk of churning.',
    inputs: ['customer_activity', 'support_history', 'usage_data'],
    outputs: ['risk_score', 'warning_signals', 'recommended_actions'],
    requiredIntegrations: ['google-sheets'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Prediction Accuracy', description: 'Correct churn predictions' },
      { name: 'Intervention Success', description: 'At-risk customers retained' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 30,
    monthlyPrice: 49,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-feature-request-pipeline',
    name: 'Feature Request Pipeline',
    outcome: 'Organize and prioritize feature requests',
    domain: 'support',
    description:
      'Captures feature requests from support tickets, deduplicates, and helps prioritize by impact.',
    inputs: ['request_content', 'customer_context'],
    outputs: ['categorized_request', 'linked_requests', 'impact_score'],
    requiredIntegrations: ['linear', 'notion'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Capture Rate', description: 'Requests captured' },
      { name: 'Dedup Accuracy', description: 'Correct groupings' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Buildable on request',
  },
  {
    id: 'agent-customer-onboarding-nudger',
    name: 'Customer Onboarding Nudger',
    outcome: 'Guide new customers to success',
    domain: 'support',
    description:
      'Monitors new customer progress and sends personalized nudges to help them complete onboarding.',
    inputs: ['customer_id', 'onboarding_steps', 'progress'],
    outputs: ['nudge_sent', 'next_action', 'health_score'],
    requiredIntegrations: ['gmail', 'slack'],
    workflows: [],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Onboarding Completion', description: 'Customers completing onboarding' },
      { name: 'Time to Value', description: 'Days to first value' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 30,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-kb-gap-finder',
    name: 'Support Knowledge Gap Finder',
    outcome: 'Identify missing KB articles',
    domain: 'support',
    description: 'Analyzes support tickets to identify topics not covered in the knowledge base.',
    inputs: ['ticket_history', 'kb_content'],
    outputs: ['gap_topics', 'suggested_articles', 'priority_score'],
    requiredIntegrations: ['notion', 'openai'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Gaps Identified', description: 'Missing topics found' },
      { name: 'KB Coverage', description: 'Topic coverage improvement' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-internal-qa-reviewer',
    name: 'Internal QA Reviewer',
    outcome: 'Automated support quality assurance',
    domain: 'support',
    description: 'Reviews support responses for quality, tone, and accuracy against guidelines.',
    inputs: ['response_content', 'qa_criteria'],
    outputs: ['qa_score', 'feedback', 'improvement_suggestions'],
    requiredIntegrations: ['openai'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Review Coverage', description: 'Responses reviewed' },
      { name: 'Quality Improvement', description: 'Score trend' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 20,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Buildable on request',
  },
  {
    id: 'agent-escalation-postmortem-builder',
    name: 'Escalation Postmortem Builder',
    outcome: 'Learn from every escalation',
    domain: 'support',
    description:
      'Automatically generates postmortem reports for resolved escalations with learnings.',
    inputs: ['escalation_data', 'resolution_notes'],
    outputs: ['postmortem_report', 'learnings', 'action_items'],
    requiredIntegrations: ['notion', 'slack'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Postmortem Coverage', description: 'Escalations documented' },
      { name: 'Learning Implementation', description: 'Actions completed' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 20,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
  },
];
