import type { AgentTemplate } from '../../fleetops/types'

// Core / Transversal agents (12)
export const coreAgentTemplates: AgentTemplate[] = [
  {
    id: 'agent-omnichannel-intake-router',
    name: 'Omnichannel Intake Router',
    outcome: 'Unified intake across email, Slack, and chat',
    domain: 'core',
    description: 'Routes incoming requests from multiple channels (email, Slack, chat) to the appropriate workflow or team based on content and urgency.',
    inputs: ['message_content', 'channel_source', 'sender_info'],
    outputs: ['routed_destination', 'priority', 'extracted_intent'],
    requiredIntegrations: ['gmail', 'slack'],
    workflows: ['wf-01', 'wf-02', 'wf-24'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Routing Accuracy', description: 'Correct destination rate' },
      { name: 'Response Time', description: 'Time from intake to routing' },
    ],
    complexity: 'M',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 20,
    monthlyPrice: null,
    availability: 'available',
    audience: 'both',
    catalogGroup: 'core',
    family: 'inbox-intake',
    tags: ['routing', 'intake', 'omnichannel'],
    visibility: 'public',
  },
  {
    id: 'agent-action-extractor',
    name: 'Action Extractor',
    outcome: 'Extract actionable items from any text',
    domain: 'core',
    description: 'Analyzes documents, emails, and messages to extract action items, deadlines, and responsible parties.',
    inputs: ['text_content', 'context'],
    outputs: ['action_items', 'deadlines', 'assignees'],
    requiredIntegrations: ['openai'],
    workflows: ['wf-09'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Extraction Accuracy', description: 'Correct action identification' },
      { name: 'Coverage', description: 'Actions captured vs manual review' },
    ],
    complexity: 'S',
    version: '0.9.0',
    channel: 'beta',
    setupTimeMinutes: 10,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'both',
    statusNote: 'Custom workflow required',
    catalogGroup: 'core',
    family: 'extraction',
    tags: ['extraction', 'action-items', 'ai'],
    visibility: 'public',
  },
  {
    id: 'agent-document-structured-data-operator',
    name: 'Document to Structured Data Operator',
    outcome: 'Transform documents into structured data',
    domain: 'core',
    description: 'Converts unstructured documents (PDFs, images, emails) into structured JSON or database records.',
    inputs: ['document', 'schema_template'],
    outputs: ['structured_data', 'confidence_scores'],
    requiredIntegrations: ['openai', 'google-drive'],
    workflows: ['wf-25', 'wf-26'],
    riskLevel: 'low',
    hitl: 'recommended',
    kpis: [
      { name: 'Extraction Accuracy', description: 'Field accuracy rate' },
      { name: 'Processing Speed', description: 'Documents per minute' },
    ],
    complexity: 'M',
    version: '0.9.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'both',
    statusNote: 'Coming soon',
    catalogGroup: 'core',
    family: 'documents-attachments',
    tags: ['documents', 'extraction', 'structured-data'],
    visibility: 'public',
  },
  {
    id: 'agent-rag-answer-copilot',
    name: 'RAG Answer Copilot',
    outcome: 'Answer questions using your knowledge base',
    domain: 'core',
    description: 'Retrieval-augmented generation agent that answers questions by searching your internal documentation and knowledge bases.',
    inputs: ['question', 'context_filters'],
    outputs: ['answer', 'sources', 'confidence'],
    requiredIntegrations: ['qdrant', 'openai'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Answer Accuracy', description: 'User-validated correctness' },
      { name: 'Source Relevance', description: 'Cited sources usefulness' },
    ],
    complexity: 'L',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 45,
    monthlyPrice: 49,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Custom workflow required',
    catalogGroup: 'core',
    family: 'knowledge-base',
    tags: ['rag', 'knowledge-base', 'qa'],
    visibility: 'public',
    featured: true,
  },
  {
    id: 'agent-n8n-commander',
    name: 'Workflow Orchestrator (n8n Commander)',
    outcome: 'Orchestrate complex multi-workflow operations',
    domain: 'core',
    description: 'Meta-agent that coordinates multiple n8n workflows, manages dependencies, and handles error recovery.',
    inputs: ['workflow_ids', 'execution_params', 'dependencies'],
    outputs: ['execution_status', 'results', 'error_log'],
    requiredIntegrations: ['openai'],
    workflows: [],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Orchestration Success', description: 'Successful multi-workflow runs' },
      { name: 'Error Recovery', description: 'Auto-recovered failures' },
    ],
    complexity: 'L',
    version: '0.7.0',
    channel: 'beta',
    setupTimeMinutes: 60,
    monthlyPrice: 79,
    availability: 'planned',
    audience: 'both',
    statusNote: 'Buildable on request',
    catalogGroup: 'core',
    family: 'governance-fleetops',
    tags: ['orchestration', 'n8n', 'workflows'],
    visibility: 'public',
  },
  {
    id: 'agent-follow-up-nudge-manager',
    name: 'Follow-up & Nudge Manager',
    outcome: 'Never let important items slip through the cracks',
    domain: 'core',
    description: 'Tracks pending items and sends intelligent reminders when follow-ups are needed.',
    inputs: ['tracked_items', 'follow_up_rules'],
    outputs: ['nudge_sent', 'status_update'],
    requiredIntegrations: ['gmail', 'slack'],
    workflows: [],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Follow-up Rate', description: 'Items followed up on time' },
      { name: 'Resolution Rate', description: 'Items resolved after nudge' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 20,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Custom workflow required',
    catalogGroup: 'core',
    family: 'follow-up',
    tags: ['follow-up', 'reminders', 'nudge'],
    visibility: 'public',
  },
  {
    id: 'agent-data-hygiene-bot',
    name: 'Data Hygiene Bot',
    outcome: 'Keep your data clean and consistent',
    domain: 'core',
    description: 'Monitors databases and CRMs for data quality issues, duplicates, and inconsistencies.',
    inputs: ['data_source', 'quality_rules'],
    outputs: ['issues_found', 'auto_fixes', 'report'],
    requiredIntegrations: ['google-sheets'],
    workflows: [],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Data Quality Score', description: 'Overall data cleanliness' },
      { name: 'Issues Resolved', description: 'Auto-fixed problems' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 30,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
    catalogGroup: 'core',
    family: 'data-hygiene',
    tags: ['data-quality', 'deduplication', 'crm'],
    visibility: 'public',
  },
  {
    id: 'agent-monitoring-digest-publisher',
    name: 'Monitoring & Digest Publisher',
    outcome: 'Stay informed with automated digests',
    domain: 'core',
    description: 'Aggregates monitoring data from multiple sources and publishes scheduled digests to your preferred channels.',
    inputs: ['data_sources', 'digest_format', 'schedule'],
    outputs: ['digest', 'highlights', 'alerts'],
    requiredIntegrations: ['slack', 'google-sheets'],
    workflows: ['wf-03', 'wf-11', 'wf-13', 'wf-14'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Digest Timeliness', description: 'On-time delivery rate' },
      { name: 'Engagement', description: 'Digest open and action rates' },
    ],
    complexity: 'M',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'available',
    audience: 'both',
    catalogGroup: 'core',
    family: 'research-intel',
    tags: ['digest', 'monitoring', 'publishing'],
    visibility: 'variant',
    variantOf: 'agent-market-monitor',
  },
  {
    id: 'agent-ai-cost-quality-governor',
    name: 'AI Cost & Quality Governor',
    outcome: 'Optimize AI spend while maintaining quality',
    domain: 'core',
    description: 'Monitors AI API usage, costs, and output quality across all agents to optimize performance and spending.',
    inputs: ['usage_data', 'quality_metrics', 'budget'],
    outputs: ['cost_report', 'quality_score', 'recommendations'],
    requiredIntegrations: ['openai'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Cost Savings', description: 'Monthly AI cost reduction' },
      { name: 'Quality Maintained', description: 'Quality score stability' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 20,
    monthlyPrice: 29,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
    catalogGroup: 'core',
    family: 'governance-fleetops',
    tags: ['cost', 'quality', 'ai-governance'],
    visibility: 'public',
  },
  {
    id: 'agent-approval-gatekeeper',
    name: 'Approval Gatekeeper',
    outcome: 'Centralized approval management',
    domain: 'core',
    description: 'Manages approval workflows across all agents, routing requests to the right approvers and tracking decisions.',
    inputs: ['approval_request', 'approver_rules'],
    outputs: ['decision', 'audit_log'],
    requiredIntegrations: ['slack', 'gmail'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'required',
    kpis: [
      { name: 'Approval Speed', description: 'Time to decision' },
      { name: 'Compliance', description: 'Policy adherence rate' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 25,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Buildable on request',
    catalogGroup: 'core',
    family: 'governance-fleetops',
    tags: ['approvals', 'hitl', 'governance'],
    visibility: 'public',
  },
  {
    id: 'agent-security-scanner',
    name: 'Security Scanner for Workflows',
    outcome: 'Detect security issues in your workflows',
    domain: 'core',
    description: 'Scans n8n workflows for security vulnerabilities, exposed credentials, and risky configurations.',
    inputs: ['workflow_definitions'],
    outputs: ['security_report', 'risk_score', 'remediation_steps'],
    requiredIntegrations: [],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Issues Found', description: 'Security issues detected' },
      { name: 'Remediation Rate', description: 'Issues fixed after scan' },
    ],
    complexity: 'M',
    version: '0.7.0',
    channel: 'beta',
    setupTimeMinutes: 15,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Coming soon',
    catalogGroup: 'core',
    family: 'governance-fleetops',
    tags: ['security', 'scanning', 'vulnerabilities'],
    visibility: 'public',
  },
  {
    id: 'agent-template-installer',
    name: 'Template Installer (Pack Manager)',
    outcome: 'Streamlined agent and pack installation',
    domain: 'core',
    description: 'Manages the installation, configuration, and updates of agent templates and packs.',
    inputs: ['template_id', 'config_params'],
    outputs: ['installation_status', 'configured_agent'],
    requiredIntegrations: [],
    workflows: [],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Install Success', description: 'Successful installations' },
      { name: 'Setup Time', description: 'Average configuration time' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 10,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'business',
    statusNote: 'Buildable on request',
    catalogGroup: 'core',
    family: 'governance-fleetops',
    tags: ['installation', 'templates', 'packs'],
    visibility: 'hidden',
  },
]
