import type { AgentTemplate } from '../../control-plane/types'

// Personal / Creator / Productivity agents (10)
export const personalAgentTemplates: AgentTemplate[] = [
  {
    id: 'agent-read-later-to-action',
    name: 'Read-Later to Action',
    outcome: 'Turn saved articles into actions',
    domain: 'productivity',
    description: 'Processes articles from your read-later queue and extracts actionable insights and tasks.',
    inputs: ['article_url', 'context', 'action_types'],
    outputs: ['summary', 'action_items', 'key_takeaways'],
    requiredIntegrations: ['apify', 'openai'],
    workflows: ['wf-09'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Articles Processed', description: 'Queue items handled' },
      { name: 'Actions Extracted', description: 'Useful actions found' },
    ],
    complexity: 'S',
    version: '0.9.0',
    channel: 'beta',
    setupTimeMinutes: 15,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'personal',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-daily-news-digest',
    name: 'Daily News Digest',
    outcome: 'Personalized daily news briefing',
    domain: 'productivity',
    description: 'Curates and summarizes news from your preferred sources delivered daily.',
    inputs: ['news_sources', 'topics', 'delivery_time'],
    outputs: ['digest', 'top_stories', 'quick_takes'],
    requiredIntegrations: ['rss', 'openai', 'slack'],
    workflows: ['wf-03', 'wf-08'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Digest Relevance', description: 'Story relevance score' },
      { name: 'Time Saved', description: 'Minutes saved daily' },
    ],
    complexity: 'M',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 15,
    monthlyPrice: null,
    availability: 'available',
    audience: 'personal',
  },
  {
    id: 'agent-personal-inbox-zero',
    name: 'Personal Inbox Zero',
    outcome: 'Achieve inbox zero automatically',
    domain: 'productivity',
    description: 'Personal email assistant that categorizes, prioritizes, and drafts responses for your inbox.',
    inputs: ['email_content', 'priorities', 'response_style'],
    outputs: ['category', 'priority', 'suggested_action', 'draft_reply'],
    requiredIntegrations: ['gmail', 'openai'],
    workflows: ['wf-01'],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Inbox Processed', description: 'Emails handled daily' },
      { name: 'Time to Inbox Zero', description: 'Minutes to clear inbox' },
    ],
    complexity: 'M',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 20,
    monthlyPrice: null,
    availability: 'available',
    audience: 'personal',
    catalogGroup: 'personal',
    family: 'inbox-intake',
    tags: ['email', 'inbox-zero', 'productivity'],
    visibility: 'variant',
    variantOf: 'agent-inbox-triage',
  },
  {
    id: 'agent-attachment-auto-archive',
    name: 'Attachment Auto-Archive',
    outcome: 'Never lose personal attachments',
    domain: 'productivity',
    description: 'Automatically archives email attachments to organized cloud storage folders.',
    inputs: ['email_attachments', 'organization_rules'],
    outputs: ['archived_files', 'folder_path', 'metadata'],
    requiredIntegrations: ['gmail', 'google-drive'],
    workflows: ['wf-26'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Files Archived', description: 'Attachments saved' },
      { name: 'Organization Score', description: 'Files findable quickly' },
    ],
    complexity: 'S',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 10,
    monthlyPrice: null,
    availability: 'available',
    audience: 'personal',
    catalogGroup: 'personal',
    family: 'documents-attachments',
    tags: ['attachments', 'archiving', 'drive'],
    visibility: 'variant',
    variantOf: 'agent-attachment-archiver',
  },
  {
    id: 'agent-learning-notes-synthesizer',
    name: 'Learning Notes Synthesizer',
    outcome: 'Transform notes into knowledge',
    domain: 'education',
    description: 'Synthesizes learning notes, highlights connections, and creates study materials.',
    inputs: ['notes', 'topic', 'learning_goals'],
    outputs: ['synthesis', 'connections', 'flashcards', 'summary'],
    requiredIntegrations: ['notion', 'openai'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Notes Processed', description: 'Notes synthesized' },
      { name: 'Knowledge Retention', description: 'Self-reported retention' },
    ],
    complexity: 'M',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 20,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'personal',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-research-newsletter-draft',
    name: 'Research to Newsletter Draft',
    outcome: 'Turn research into newsletter content',
    domain: 'creator',
    description: 'Transforms research findings into newsletter-ready content with your writing style.',
    inputs: ['research_topic', 'style_guide', 'newsletter_format'],
    outputs: ['newsletter_draft', 'subject_lines', 'key_points'],
    requiredIntegrations: ['perplexity'],
    workflows: ['wf-22'],
    riskLevel: 'medium',
    hitl: 'recommended',
    kpis: [
      { name: 'Draft Quality', description: 'Edits required' },
      { name: 'Time Saved', description: 'Hours saved per issue' },
    ],
    complexity: 'M',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 20,
    monthlyPrice: null,
    availability: 'available',
    audience: 'personal',
  },
  {
    id: 'agent-habit-progress-reporter',
    name: 'Habit & Progress Reporter',
    outcome: 'Track and report on personal habits',
    domain: 'productivity',
    description: 'Monitors habit tracking data and generates progress reports with insights.',
    inputs: ['habit_data', 'goals', 'report_frequency'],
    outputs: ['progress_report', 'trends', 'recommendations', 'streaks'],
    requiredIntegrations: ['google-sheets'],
    workflows: [],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Report Usefulness', description: 'Self-reported value' },
      { name: 'Habit Consistency', description: 'Streak maintenance' },
    ],
    complexity: 'S',
    version: '0.8.0',
    channel: 'beta',
    setupTimeMinutes: 15,
    monthlyPrice: null,
    availability: 'planned',
    audience: 'personal',
    statusNote: 'Coming soon',
  },
  {
    id: 'agent-creator-analytics-copilot',
    name: 'Creator Analytics Copilot',
    outcome: 'Understand your content performance',
    domain: 'creator',
    description: 'Aggregates analytics from multiple platforms and provides AI-powered content insights.',
    inputs: ['platform_data', 'content_type', 'time_period'],
    outputs: ['performance_report', 'top_content', 'recommendations', 'trends'],
    requiredIntegrations: ['google-analytics', 'baserow'],
    workflows: ['wf-11', 'wf-13', 'wf-14'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Insight Quality', description: 'Actionable insights' },
      { name: 'Performance Improvement', description: 'Engagement growth' },
    ],
    complexity: 'M',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 30,
    monthlyPrice: null,
    availability: 'available',
    audience: 'personal',
  },
  {
    id: 'agent-reviews-tracker',
    name: 'Reviews Tracker',
    outcome: 'Monitor your reviews and reputation',
    domain: 'creator',
    description: 'Tracks reviews across platforms and alerts on new feedback with sentiment analysis.',
    inputs: ['review_sources', 'alert_threshold'],
    outputs: ['reviews', 'sentiment_summary', 'alerts', 'response_suggestions'],
    requiredIntegrations: ['trustpilot', 'google-sheets'],
    workflows: ['wf-10'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Review Coverage', description: 'Reviews captured' },
      { name: 'Response Time', description: 'Time to acknowledge' },
    ],
    complexity: 'S',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 15,
    monthlyPrice: null,
    availability: 'available',
    audience: 'personal',
    catalogGroup: 'personal',
    family: 'reviews-sentiment',
    tags: ['reviews', 'reputation', 'creator'],
    visibility: 'variant',
    variantOf: 'agent-sentiment-tracker',
  },
  {
    id: 'agent-meeting-prep-mini-brief',
    name: 'Meeting Prep Mini-Brief',
    outcome: 'Quick meeting prep for personal use',
    domain: 'productivity',
    description: 'Lightweight meeting prep that researches attendees and provides quick talking points.',
    inputs: ['meeting_info', 'attendees'],
    outputs: ['mini_brief', 'talking_points', 'questions'],
    requiredIntegrations: ['google-calendar', 'apify'],
    workflows: ['wf-04'],
    riskLevel: 'low',
    hitl: 'optional',
    kpis: [
      { name: 'Prep Coverage', description: 'Meetings with briefs' },
      { name: 'Prep Time', description: 'Minutes to prepare' },
    ],
    complexity: 'S',
    version: '1.0.0',
    channel: 'stable',
    setupTimeMinutes: 15,
    monthlyPrice: null,
    availability: 'available',
    audience: 'personal',
    catalogGroup: 'personal',
    family: 'meeting-scheduling',
    tags: ['meeting', 'prep', 'quick'],
    visibility: 'variant',
    variantOf: 'agent-meeting-prep',
  },
]
