import type { Integration } from '../../control-plane/types'

// New integrations to add
export const newIntegrations: Integration[] = [
  {
    id: 'rss',
    name: 'RSS Feeds',
    icon: 'rss',
    category: 'dev',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['read'],
    lastTestAt: null,
  },
  {
    id: 'jina',
    name: 'Jina AI',
    icon: 'brain',
    category: 'dev',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['embeddings', 'rerank'],
    lastTestAt: null,
  },
  {
    id: 'qdrant',
    name: 'Qdrant',
    icon: 'database',
    category: 'dev',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['collections:read', 'collections:write', 'points:read', 'points:write'],
    lastTestAt: null,
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    icon: 'brain',
    category: 'dev',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['chat', 'embeddings'],
    lastTestAt: null,
  },
  {
    id: 'excel',
    name: 'Excel (Local)',
    icon: 'table',
    category: 'productivity',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['read', 'write'],
    lastTestAt: null,
  },
  {
    id: 'nocodb',
    name: 'NocoDB',
    icon: 'database',
    category: 'productivity',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['tables:read', 'tables:write', 'records:read', 'records:write'],
    lastTestAt: null,
  },
  {
    id: 'baserow',
    name: 'Baserow',
    icon: 'table',
    category: 'productivity',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['database:read', 'database:write'],
    lastTestAt: null,
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    icon: 'brain',
    category: 'dev',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['chat'],
    lastTestAt: null,
  },
  {
    id: 'serpbear',
    name: 'SERPBear',
    icon: 'search',
    category: 'dev',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['keywords:read', 'rankings:read'],
    lastTestAt: null,
  },
  {
    id: 'umami',
    name: 'Umami Analytics',
    icon: 'bar-chart',
    category: 'dev',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['stats:read', 'websites:read'],
    lastTestAt: null,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    icon: 'brain',
    category: 'dev',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['chat', 'code'],
    lastTestAt: null,
  },
  {
    id: 'python',
    name: 'Python Runtime',
    icon: 'code',
    category: 'dev',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['execute'],
    lastTestAt: null,
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    icon: 'search',
    category: 'dev',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['search', 'chat'],
    lastTestAt: null,
  },
  {
    id: 'google-analytics',
    name: 'Google Analytics',
    icon: 'bar-chart',
    category: 'productivity',
    status: 'disconnected',
    scopes: [],
    requiredScopes: ['analytics.readonly'],
    lastTestAt: null,
    oauthUrl: '/api/oauth/google-analytics',
  },
]
