import type { WorkflowTemplate } from '../../control-plane/types'

// Planned workflow placeholders to support orphan planned agents
export const plannedWorkflowTemplates: WorkflowTemplate[] = [
  {
    id: 'wf-plan-webhook-intake-base',
    name: 'Universal Webhook Intake',
    summary: 'Base webhook endpoint for routing incoming requests to appropriate handlers',
    trigger: 'webhook',
    integrations: ['openai'],
    output: 'Routed requests to appropriate downstream workflows',
    useCase: 'Foundation for multi-channel intake agents',
    riskLevel: 'low',
    version: '0.1.0',
    changelog: ['0.1.0: Initial planned release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Webhook', description: 'Receive request' },
      { id: 'n2', type: 'ai', name: 'Intent Detection', description: 'Classify request type' },
      { id: 'n3', type: 'logic', name: 'Router', description: 'Route to handler' },
    ],
    availability: 'planned',
    statusNote: 'Coming Q2',
    catalogGroups: ['core'],
    family: 'intake',
    tags: ['webhook', 'routing', 'foundation'],
    visibility: 'public',
  },
  {
    id: 'wf-plan-extract-actions',
    name: 'Action Item Extractor',
    summary: 'Extract actionable items from documents, emails, and meeting notes',
    trigger: 'webhook',
    integrations: ['openai'],
    output: 'Structured list of action items with owners and deadlines',
    useCase: 'Turn unstructured content into trackable tasks',
    riskLevel: 'low',
    version: '0.1.0',
    changelog: ['0.1.0: Initial planned release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Webhook', description: 'Receive content' },
      { id: 'n2', type: 'ai', name: 'AI Extract', description: 'Identify actions' },
      { id: 'n3', type: 'logic', name: 'Structure', description: 'Format output' },
    ],
    availability: 'planned',
    statusNote: 'Coming Q2',
    catalogGroups: ['core'],
    family: 'extraction',
    tags: ['extraction', 'actions', 'tasks'],
    visibility: 'public',
  },
  {
    id: 'wf-plan-pdf-to-structured-data',
    name: 'PDF to Structured Data',
    summary: 'Convert PDF documents into structured JSON with field extraction',
    trigger: 'webhook',
    integrations: ['openai', 'google-drive'],
    output: 'Structured JSON data extracted from PDF',
    useCase: 'Digitize forms, invoices, and contracts',
    riskLevel: 'low',
    version: '0.1.0',
    changelog: ['0.1.0: Initial planned release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Webhook', description: 'Receive PDF URL' },
      { id: 'n2', type: 'extract', name: 'PDF Parse', description: 'Extract text' },
      { id: 'n3', type: 'ai', name: 'Structure', description: 'Map to schema' },
    ],
    availability: 'planned',
    statusNote: 'Coming Q2',
    catalogGroups: ['core', 'ops'],
    family: 'extraction',
    tags: ['pdf', 'documents', 'extraction'],
    visibility: 'public',
  },
  {
    id: 'wf-plan-rag-kb-answer',
    name: 'RAG Knowledge Base Answer',
    summary: 'Answer questions using retrieval-augmented generation from your knowledge base',
    trigger: 'webhook',
    integrations: ['qdrant', 'openai'],
    output: 'Answer with source citations and confidence score',
    useCase: 'Build internal Q&A systems backed by company knowledge',
    riskLevel: 'low',
    version: '0.1.0',
    changelog: ['0.1.0: Initial planned release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Webhook', description: 'Receive question' },
      { id: 'n2', type: 'ai', name: 'Vector Search', description: 'Find relevant docs' },
      { id: 'n3', type: 'ai', name: 'Generate Answer', description: 'Synthesize response' },
    ],
    availability: 'planned',
    statusNote: 'Coming Q2',
    catalogGroups: ['core', 'support'],
    family: 'knowledge-base',
    tags: ['rag', 'knowledge-base', 'qa'],
    featured: true,
    visibility: 'public',
  },
  {
    id: 'wf-plan-follow-up-sequences',
    name: 'Follow-up Sequence Engine',
    summary: 'Manage multi-step follow-up sequences with intelligent timing',
    trigger: 'cron',
    integrations: ['gmail', 'slack', 'google-sheets'],
    output: 'Automated follow-up messages sent at optimal times',
    useCase: 'Never let important items slip through the cracks',
    riskLevel: 'medium',
    version: '0.1.0',
    changelog: ['0.1.0: Initial planned release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Schedule', description: 'Check pending items' },
      { id: 'n2', type: 'logic', name: 'Evaluate', description: 'Determine actions' },
      { id: 'n3', type: 'action', name: 'Send', description: 'Execute follow-up' },
    ],
    availability: 'planned',
    statusNote: 'Coming Q2',
    catalogGroups: ['core', 'sales'],
    family: 'follow-up',
    tags: ['follow-up', 'sequences', 'reminders'],
    visibility: 'public',
  },
  {
    id: 'wf-plan-data-hygiene-sweep',
    name: 'Data Hygiene Sweep',
    summary: 'Scan and clean data sources for quality issues and duplicates',
    trigger: 'cron',
    integrations: ['google-sheets'],
    output: 'Data quality report with auto-fix recommendations',
    useCase: 'Maintain clean, consistent data across systems',
    riskLevel: 'medium',
    version: '0.1.0',
    changelog: ['0.1.0: Initial planned release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Schedule', description: 'Weekly scan' },
      { id: 'n2', type: 'logic', name: 'Analyze', description: 'Find issues' },
      { id: 'n3', type: 'action', name: 'Report', description: 'Generate findings' },
    ],
    availability: 'planned',
    statusNote: 'Coming Q3',
    catalogGroups: ['core', 'ops'],
    family: 'data-hygiene',
    tags: ['data-quality', 'cleaning', 'deduplication'],
    visibility: 'public',
  },
  {
    id: 'wf-plan-hitl-approvals',
    name: 'HITL Approval Gateway',
    summary: 'Centralized approval workflow for high-risk agent actions',
    trigger: 'webhook',
    integrations: ['slack', 'gmail'],
    output: 'Approval decision with audit trail',
    useCase: 'Keep humans in control of sensitive operations',
    riskLevel: 'low',
    version: '0.1.0',
    changelog: ['0.1.0: Initial planned release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Webhook', description: 'Approval request' },
      { id: 'n2', type: 'action', name: 'Notify', description: 'Alert approver' },
      { id: 'n3', type: 'logic', name: 'Wait', description: 'Await decision' },
    ],
    availability: 'planned',
    statusNote: 'Coming Q2',
    catalogGroups: ['core'],
    family: 'governance-platform',
    tags: ['hitl', 'approvals', 'governance'],
    visibility: 'public',
  },
  {
    id: 'wf-plan-security-scan',
    name: 'Workflow Security Scanner',
    summary: 'Scan n8n workflows for security vulnerabilities and best practice violations',
    trigger: 'manual',
    integrations: [],
    output: 'Security report with risk scores and remediation steps',
    useCase: 'Ensure workflow security before deployment',
    riskLevel: 'low',
    version: '0.1.0',
    changelog: ['0.1.0: Initial planned release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Manual', description: 'Start scan' },
      { id: 'n2', type: 'logic', name: 'Analyze', description: 'Check patterns' },
      { id: 'n3', type: 'action', name: 'Report', description: 'Generate findings' },
    ],
    availability: 'planned',
    statusNote: 'Coming Q3',
    catalogGroups: ['core'],
    family: 'governance-platform',
    tags: ['security', 'scanning', 'compliance'],
    visibility: 'public',
  },
  {
    id: 'wf-plan-support-ops-core',
    name: 'Support Ops Foundation',
    summary: 'Core support operations workflow for ticket handling and customer context',
    trigger: 'webhook',
    integrations: ['linear', 'slack', 'openai'],
    output: 'Enriched ticket with context and suggested actions',
    useCase: 'Foundation for support automation agents',
    riskLevel: 'low',
    version: '0.1.0',
    changelog: ['0.1.0: Initial planned release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Webhook', description: 'Ticket event' },
      { id: 'n2', type: 'fetch', name: 'Context', description: 'Gather customer data' },
      { id: 'n3', type: 'ai', name: 'Analyze', description: 'Generate insights' },
    ],
    availability: 'planned',
    statusNote: 'Coming Q2',
    catalogGroups: ['support'],
    family: 'ticketing',
    tags: ['support', 'ticketing', 'foundation'],
    visibility: 'public',
  },
  {
    id: 'wf-plan-sales-ops-core',
    name: 'Sales Ops Foundation',
    summary: 'Core sales operations workflow for deal tracking and pipeline management',
    trigger: 'cron',
    integrations: ['google-sheets', 'slack', 'openai'],
    output: 'Pipeline insights and recommended actions',
    useCase: 'Foundation for sales automation agents',
    riskLevel: 'low',
    version: '0.1.0',
    changelog: ['0.1.0: Initial planned release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Schedule', description: 'Daily check' },
      { id: 'n2', type: 'fetch', name: 'Pipeline', description: 'Get deal data' },
      { id: 'n3', type: 'ai', name: 'Analyze', description: 'Generate insights' },
    ],
    availability: 'planned',
    statusNote: 'Coming Q2',
    catalogGroups: ['sales'],
    family: 'sales-ops',
    tags: ['sales', 'pipeline', 'foundation'],
    visibility: 'public',
  },
  {
    id: 'wf-plan-content-engine',
    name: 'Content Engine',
    summary: 'Automated content creation and repurposing workflow',
    trigger: 'manual',
    integrations: ['openai', 'notion'],
    output: 'Multi-format content from single source',
    useCase: 'Scale content production without scaling team',
    riskLevel: 'medium',
    version: '0.1.0',
    changelog: ['0.1.0: Initial planned release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Manual', description: 'Provide source' },
      { id: 'n2', type: 'ai', name: 'Generate', description: 'Create variants' },
      { id: 'n3', type: 'action', name: 'Publish', description: 'Save outputs' },
    ],
    availability: 'planned',
    statusNote: 'Coming Q3',
    catalogGroups: ['marketing'],
    family: 'content',
    tags: ['content', 'repurposing', 'marketing'],
    visibility: 'public',
  },
  {
    id: 'wf-plan-brand-monitoring',
    name: 'Brand Monitoring Pipeline',
    summary: 'Monitor brand mentions across web and social with sentiment analysis',
    trigger: 'cron',
    integrations: ['apify', 'openai', 'slack'],
    output: 'Brand mention alerts with sentiment scores',
    useCase: 'Stay on top of brand reputation',
    riskLevel: 'low',
    version: '0.1.0',
    changelog: ['0.1.0: Initial planned release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Schedule', description: 'Hourly scan' },
      { id: 'n2', type: 'fetch', name: 'Scrape', description: 'Find mentions' },
      { id: 'n3', type: 'ai', name: 'Analyze', description: 'Score sentiment' },
    ],
    availability: 'planned',
    statusNote: 'Coming Q3',
    catalogGroups: ['marketing'],
    family: 'monitoring',
    tags: ['brand', 'monitoring', 'sentiment'],
    visibility: 'public',
  },
  {
    id: 'wf-plan-finance-collections',
    name: 'Collections & Aging Pipeline',
    summary: 'Track overdue invoices and automate collection follow-ups',
    trigger: 'cron',
    integrations: ['google-sheets', 'gmail'],
    output: 'Aging reports and automated collection nudges',
    useCase: 'Improve cash flow with automated collections',
    riskLevel: 'medium',
    version: '0.1.0',
    changelog: ['0.1.0: Initial planned release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Schedule', description: 'Daily check' },
      { id: 'n2', type: 'logic', name: 'Aging', description: 'Calculate overdue' },
      { id: 'n3', type: 'action', name: 'Nudge', description: 'Send reminders' },
    ],
    availability: 'planned',
    statusNote: 'Coming Q3',
    catalogGroups: ['finance'],
    family: 'finance',
    tags: ['collections', 'invoicing', 'aging'],
    visibility: 'public',
  },
  {
    id: 'wf-plan-internal-ops-router',
    name: 'Internal Request Router',
    summary: 'Route internal team requests to appropriate handlers',
    trigger: 'webhook',
    integrations: ['slack', 'linear'],
    output: 'Routed request with context and SLA',
    useCase: 'Streamline internal operations requests',
    riskLevel: 'low',
    version: '0.1.0',
    changelog: ['0.1.0: Initial planned release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Webhook', description: 'Receive request' },
      { id: 'n2', type: 'ai', name: 'Classify', description: 'Determine type' },
      { id: 'n3', type: 'action', name: 'Route', description: 'Assign handler' },
    ],
    availability: 'planned',
    statusNote: 'Coming Q2',
    catalogGroups: ['ops'],
    family: 'ops',
    tags: ['routing', 'internal', 'ops'],
    visibility: 'public',
  },
  {
    id: 'wf-plan-hr-hiring-pipeline',
    name: 'Hiring Pipeline Automation',
    summary: 'Automate candidate tracking and interview coordination',
    trigger: 'webhook',
    integrations: ['gmail', 'google-calendar', 'google-sheets'],
    output: 'Scheduled interviews and candidate status updates',
    useCase: 'Speed up hiring with automated coordination',
    riskLevel: 'medium',
    version: '0.1.0',
    changelog: ['0.1.0: Initial planned release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Webhook', description: 'Application event' },
      { id: 'n2', type: 'logic', name: 'Evaluate', description: 'Check criteria' },
      { id: 'n3', type: 'action', name: 'Schedule', description: 'Book interviews' },
    ],
    availability: 'planned',
    statusNote: 'Coming Q3',
    catalogGroups: ['ops'],
    family: 'hr-hiring',
    tags: ['hiring', 'hr', 'interviews'],
    visibility: 'public',
  },
  {
    id: 'wf-plan-order-support-ops',
    name: 'Order Support Operations',
    summary: 'Handle order inquiries with status lookup and resolution',
    trigger: 'webhook',
    integrations: ['gmail', 'google-sheets', 'slack'],
    output: 'Order status with resolution actions',
    useCase: 'Automate common order support inquiries',
    riskLevel: 'medium',
    version: '0.1.0',
    changelog: ['0.1.0: Initial planned release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Webhook', description: 'Support request' },
      { id: 'n2', type: 'fetch', name: 'Lookup', description: 'Get order status' },
      { id: 'n3', type: 'action', name: 'Respond', description: 'Send update' },
    ],
    availability: 'planned',
    statusNote: 'Coming Q3',
    catalogGroups: ['support', 'ops'],
    family: 'ecommerce',
    tags: ['ecommerce', 'orders', 'support'],
    visibility: 'public',
  },
  {
    id: 'wf-plan-ai-inventory-retention',
    name: 'AI Inventory & Retention',
    summary: 'Track AI model usage and manage data retention policies',
    trigger: 'cron',
    integrations: ['google-sheets'],
    output: 'Inventory report and retention actions',
    useCase: 'Governance over AI assets and data lifecycle',
    riskLevel: 'low',
    version: '0.1.0',
    changelog: ['0.1.0: Initial planned release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Schedule', description: 'Weekly audit' },
      { id: 'n2', type: 'logic', name: 'Analyze', description: 'Check policies' },
      { id: 'n3', type: 'action', name: 'Report', description: 'Generate inventory' },
    ],
    availability: 'planned',
    statusNote: 'Coming Q3',
    catalogGroups: ['core', 'ops'],
    family: 'governance-platform',
    tags: ['inventory', 'retention', 'governance'],
    visibility: 'public',
  },
  {
    id: 'wf-plan-learning-notes',
    name: 'Learning Notes Pipeline',
    summary: 'Process and synthesize learning materials into study aids',
    trigger: 'manual',
    integrations: ['notion', 'openai'],
    output: 'Synthesized notes with flashcards and summaries',
    useCase: 'Transform notes into effective study materials',
    riskLevel: 'low',
    version: '0.1.0',
    changelog: ['0.1.0: Initial planned release'],
    nodesOverview: [
      { id: 'n1', type: 'trigger', name: 'Manual', description: 'Provide notes' },
      { id: 'n2', type: 'ai', name: 'Synthesize', description: 'Create materials' },
      { id: 'n3', type: 'action', name: 'Save', description: 'Store in Notion' },
    ],
    availability: 'planned',
    statusNote: 'Coming Q3',
    catalogGroups: ['personal'],
    family: 'learning',
    tags: ['learning', 'notes', 'education'],
    visibility: 'public',
  },
]
